### ISSUE TITLE
Additional field -> user can make his own entries

### ISSUE THREAD

**Issue by frankdema** [sa-si-dev/virtual-select#1]
Great script. Thanks.

I wish:

1. great were a javascript version without tooltaps and without search feature

2. an additional field (like the search field) in which the user can make his own entries that are not in the drop-down list.

**Comment by sa-si-dev** [comment]
> Great script. Thanks.
> 
> I wish:
> 
> 1. great were a javascript version without tooltaps and without search feature
> 2. an additional field (like the search field) in which the user can make his own entries that are not in the drop-down list.

@frankdema thanks for you feedback.

Regarding your request,
1.1 In the latest version, tooltip would be shown only if the text is partially hidden with ellipsis. Please use latest files.
1.2 You can remove search feature by adding property `search: false`
2. I am not getting your point. Could you please give me some sample scenario

**Comment by frankdema** [comment]
Many thanks for the answer.

to 1.
I would like to reduce the size of the javascript (and css). It should only contain what is really needed for the basic function. The Javascrit can easily be split up. In Core and Search and Tooltaps.
Then you can use what you need.

to 2.
e.g.

I have a fixed list:

aaa
bbb
ccc
ddd
eee

The user wants ccc and something that is not on the fixed list. (xxxx)
The user should have the opportunity to make an "own" entry.

e.g.
xxxx

now the list is:
aaa
bbb
ccc --> is aktiv
ddd
eee
xxxx --> is aktiv


Is that understandable?

**Comment by sa-si-dev** [comment]
Thank you for the detailed explanation.

1.1 I have already split tooltip related code. You can import and use it as an optional feature.
     Also you can use tooltip plugin in your project, if you want. (documentation https://sa-si-dev.github.io/tooltip)

1.2 I will try to split search related code in the future release.

2 I understood your point. I will implement it in the future release.

**Comment by frankdema** [comment]
That's great. Many Thanks. i'm happy.

**Comment by sa-si-dev** [comment]
@frankdema as you requested, I have implemented the feature to allow adding new entries.

This feature is available in the [release v.1.0.2](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.2) ([more details](https://sa-si-dev.github.io/virtual-select/#/examples?id=allow-to-add-new-option))
