### ISSUE TITLE
Prevent removing classes that were on the original select

### ISSUE THREAD

**Issue by FluffyDiscord** [sa-si-dev/virtual-select#100]
This plugin removes the whole "select" and replaces it with plain "input" and removes all classes and attributes from it. Would be nice, to at least keep other attributes

**Comment by Jara92** [comment]
I would prefer not removing "select" at all. This "feature" makes me mad and I have to use another library now because there is no easy option to use it with my Symfony forms. It is a shame because the plugin works well.

**Comment by sa-si-dev** [comment]
> This plugin removes the whole "select" and replaces it with plain "input" and removes all classes and attributes from it. Would be nice, to at least keep other attributes

@FluffyDiscord I will keep the classes of `select` element in the future release

**Comment by sa-si-dev** [comment]
> I would prefer not removing "select" at all. This "feature" makes me mad and I have to use another library now because there is no easy option to use it with my Symfony forms. It is a shame because the plugin works well.

I created this plugin as an alternative to native select element. The idea of this plugin is improving performance by removing unwanted DOM elements.

**Comment by sa-si-dev** [comment]
@FluffyDiscord I have updated the code to keep the class names of the native `select` element.

This feature is available in the [release v1.0.25](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.25)
