### ISSUE TITLE
multiple option can't use in vue

### ISSUE THREAD

**Issue by bunajianke** [sa-si-dev/virtual-select#105]
```js
VirtualSelect.init({
          ele: "#virtual-select",
          placeholder: "请选择...",
          options,
          search: true,
          multiple: true,
        });
```
![image](https://user-images.githubusercontent.com/32815833/154883093-ca97ef2b-fbd7-48d8-b6f9-cf9881391fef.png)

**Comment by sa-si-dev** [comment]
@bunajianke as of now this, support values for multiple attribute is true, false or no value.

**Comment by bunajianke** [comment]
> @bunajianke as of now, supported values for multiple attribute is true, false or no value.

as you see, i set the multiple value is boolean true 
```js
export default {
  name: "VirtualSelect",
  props: {
    options: { type: Array, default: () => [] },
    valueKey: { type: String, default: "label" },
    labelKey: { type: String, default: "value" },
    descriptionKey: { type: String, default: "description" },
    aliasKey: { type: String, default: "alias" }
  },
  watch: {
    options(array) {
      this.init(array);
    }
  },
  mounted() {
    this.init();
  },
  methods: {
    init(options = []) {
      const { valueKey, labelKey, descriptionKey, aliasKey } = this;
      VirtualSelect.init({
        ele: "#virtual-select",
        placeholder: "请选择...",
        options,
        search: true,
        multiple: true,
        valueKey,
        labelKey,
        descriptionKey,
        selectedValue: ["4002793", "1000102580"]
      });
    },
  }
}
```

**Comment by sa-si-dev** [comment]
> > @bunajianke as of now, supported values for multiple attribute is true, false or no value.
> 
> as you see, i set the multiple value is boolean true 
> ```js
> export default {
>   name: "VirtualSelect",
>   props: {
>     options: { type: Array, default: () => [] },
>     valueKey: { type: String, default: "label" },
>     labelKey: { type: String, default: "value" },
>     descriptionKey: { type: String, default: "description" },
>     aliasKey: { type: String, default: "alias" }
>   },
>   watch: {
>     options(array) {
>       this.init(array);
>     }
>   },
>   mounted() {
>     this.init();
>   },
>   methods: {
>     init(options = []) {
>       const { valueKey, labelKey, descriptionKey, aliasKey } = this;
>       VirtualSelect.init({
>         ele: "#virtual-select",
>         placeholder: "请选择...",
>         options,
>         search: true,
>         multiple: true,
>         valueKey,
>         labelKey,
>         descriptionKey,
>         selectedValue: ["4002793", "1000102580"]
>       });
>     },
>   }
> }
> ```

You should remove the `multiple` attribute from the `div` element.

**Comment by bunajianke** [comment]
thanks! I incorrect set the attribute in component
```html
<virtual-select
            :̶m̶u̶l̶t̶i̶p̶l̶e̶=̶"̶t̶r̶u̶e̶"̶
            :options="userOptions"
            label-key="chr_name"
            value-key="chr_id"
            description-key="chr_id"
            alias-key="filterValue"
          ></virtual-select>
```
It working
