### ISSUE TITLE
popup opens above values even when there's a lot of space below

### ISSUE THREAD

**Issue by Jaaap** [sa-si-dev/virtual-select#109]
The popup will open above the values instead of below even when there is 2x the height of the popup available as spoecae below the values.
See screenshots, the blue bar represents the footer (or the bottom of the page):

![image](https://user-images.githubusercontent.com/243016/155695788-1fd5601b-1f33-4a0a-a22d-65c289b5714d.png)

Now with the browser window a little bigger:
<img width="747" alt="image" src="https://user-images.githubusercontent.com/243016/155695621-82f9a252-cfc7-46d4-acdb-1be84d951809.png">

**Comment by sa-si-dev** [comment]
@Jaaap I will check and fix it in the future release.

**Comment by sa-si-dev** [comment]
This issue has been fixed in the [release v1.0.27](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.27)
