### ISSUE TITLE
SelectAll when multiple=true and already filtered.

### ISSUE THREAD

**Issue by joselrio** [sa-si-dev/virtual-select#114]
Hi there, 

During our implementation we're facing an issue related with select all when **multiple=true**.

When we start writing at the input and the list remains filtered if we select all, It's expected to get all the filtered options as a selected options and not all the options.

Here a video that show this behaviour.
https://user-images.githubusercontent.com/5339917/158809858-d521d448-6ab8-4137-b465-cb243d280ead.MP4

Thanks in advance!

**Comment by sa-si-dev** [comment]
Set `selectAllOnlyVisible: true` property to get this feature.

**Comment by joselrio** [comment]
Oh... sorry to raise this as an issue! My bad!
Thanks!
