### ISSUE TITLE
When opening at the top and while filtering the element gets dettached

### ISSUE THREAD

**Issue by gnbm** [sa-si-dev/virtual-select#115]
Hi. 
First of all, I have to congratulate you on the amazing work you're doing with this lib.
I found a use case that could be improved from an experience point of view that is related to the fact that when the dropdown opens at the top and we start filtering the options, the ballon with the options gets detached from the selected element as you can see on the GIF:
![DropdownDetached](https://user-images.githubusercontent.com/29493222/158908289-43ce85de-b4ce-4704-b36d-154c99bd4252.gif)

Also, how can we manage the event responsible to reattach the element when we scroll on the page?
Thank you in advance!

**Comment by sa-si-dev** [comment]
@gnbm thanks for letting me know this issue.

I will fix this issue in the future release.

For positioning drop-down I have used my another plugin [https://github.com/sa-si-dev/popper](https://github.com/sa-si-dev/popper)

**Comment by gnbm** [comment]
@sa-si-dev Do you have an estimate about when would you do a release with this fix? 
Once again, great work and thank you for the fast reply 🚀

**Comment by sa-si-dev** [comment]
This issue has been fixed in the [release v1.0.27](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.27)
