### ISSUE TITLE
Scroll issue at small screens (mobile landscape)

### ISSUE THREAD

**Issue by joselrio** [sa-si-dev/virtual-select#118]
Hi, 

I attached a gif that shows the misbehaviour when we're dealing with mobile landscape screens, where the items are not been visible at the right place inside dropdown balloon. 
After some quick tests, the issue is related with the translate calculation since the items are there but not in the right position due to that change.

Thanks for your good work!

![Untitled](https://user-images.githubusercontent.com/5339917/159471957-2f930242-21e9-489c-be2f-c769811ef192.gif)

**Comment by sa-si-dev** [comment]
@joselrio thanks for letting me know it. I will fix it in the future release.

**Comment by sa-si-dev** [comment]
@joselrio @gnbm This issue has been fixed in the [release v1.0.28](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.28)
