### ISSUE TITLE
Warnings when using "use strict"

### ISSUE THREAD

**Issue by Jaaap** [sa-si-dev/virtual-select#121]
When you enforce [Strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode), in our case because we use [closure-compiler-maven-plugin](https://github.com/blutorange/closure-compiler-maven-plugin) in ECMASCRIPT_2016 mode which does enforce strict mode as its default setting, VirtualSelect triggers a bunch of warnings:
```
Mar 25, 2022 1:38:37 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 0 error(s), 7 warning(s)
[WARNING] /some/path/resources/js/virtual-select.js [5:3]: WARNING - Suspicious code. The result of the 'not' operator is not being used.

[WARNING] /some/path/resources/js/virtual-select.js [5:1205]: WARNING - Suspicious code. The result of the 'not' operator is not being used.

[WARNING] /some/path/resources/js/virtual-select.js [5:2215]: WARNING - Left operand of && operator is always falsy.

[WARNING] /some/path/resources/js/virtual-select.js [5:3256]: WARNING - Suspicious code. The result of the 'not' operator is not being used.

[WARNING] /some/path/resources/js/virtual-select.js [5:4095]: WARNING - Left operand of && operator is always falsy.

[WARNING] /some/path/resources/js/virtual-select.js [5:4095]: WARNING - Left operand of && operator is always truthy.

[WARNING] /some/path/resources/js/virtual-select.js [5:4095]: WARNING - Suspicious code. The result of the 'not' operator is not being used.
```

The line number is always 5 because of the already-minified https://raw.githubusercontent.com/sa-si-dev/virtual-select/master/dist/virtual-select.min.js that is used to generate this report.

Would it be possible to make VirtualSelect more compatible with Strict mode?

**Comment by sa-si-dev** [comment]
> When you enforce [Strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode), in our case because we use [closure-compiler-maven-plugin](https://github.com/blutorange/closure-compiler-maven-plugin) in ECMASCRIPT_2016 mode which does enforce strict mode as its default setting, VirtualSelect triggers a bunch of warnings:
> 
> ```
> Mar 25, 2022 1:38:37 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
> WARNING: 0 error(s), 7 warning(s)
> [WARNING] /some/path/resources/js/virtual-select.js [5:3]: WARNING - Suspicious code. The result of the 'not' operator is not being used.
> 
> [WARNING] /some/path/resources/js/virtual-select.js [5:1205]: WARNING - Suspicious code. The result of the 'not' operator is not being used.
> 
> [WARNING] /some/path/resources/js/virtual-select.js [5:2215]: WARNING - Left operand of && operator is always falsy.
> 
> [WARNING] /some/path/resources/js/virtual-select.js [5:3256]: WARNING - Suspicious code. The result of the 'not' operator is not being used.
> 
> [WARNING] /some/path/resources/js/virtual-select.js [5:4095]: WARNING - Left operand of && operator is always falsy.
> 
> [WARNING] /some/path/resources/js/virtual-select.js [5:4095]: WARNING - Left operand of && operator is always truthy.
> 
> [WARNING] /some/path/resources/js/virtual-select.js [5:4095]: WARNING - Suspicious code. The result of the 'not' operator is not being used.
> ```
> 
> The line number is always 5 because of the already-minified https://raw.githubusercontent.com/sa-si-dev/virtual-select/master/dist/virtual-select.min.js that is used to generate this report.
> 
> Would it be possible to make VirtualSelect more compatible with Strict mode?

As I checked on the given line and column number, it seems those warning syntaxes are added by Webpack while optimizing code.
And, I hope that Webpack is doing that to improve the performance only.

```js
[5:3] - */!function(){
[5:4095] - "true"===o?o=!0:"false"===o&&(o=!1)
```

**Comment by Jaaap** [comment]
Is it possible to build an unminified version of the javascript and publish it next to
https://raw.githubusercontent.com/sa-si-dev/virtual-select/master/dist/virtual-select.min.js
so
https://raw.githubusercontent.com/sa-si-dev/virtual-select/master/dist/virtual-select.js
That would be *very* helpful.

**Comment by sa-si-dev** [comment]
> Is it possible to build an unminified version of the javascript and publish it next to
> https://raw.githubusercontent.com/sa-si-dev/virtual-select/master/dist/virtual-select.min.js
> so
> https://raw.githubusercontent.com/sa-si-dev/virtual-select/master/dist/virtual-select.js
> That would be *very* helpful.

I will check the possibilities and add unminified file.

**Comment by sa-si-dev** [comment]
@Jaaap I have added an uncompressed file [virtual-select.js](https://github.com/sa-si-dev/virtual-select/blob/master/dist/virtual-select.js) in the dist folder. Please check it and let me know if there is any warning in your build.
