### ISSUE TITLE
Does not show when inside an overflow css property

### ISSUE THREAD

**Issue by guilhermerover** [sa-si-dev/virtual-select#122]
When you open a select inside a div with overflow css property, this happend:
![image](https://user-images.githubusercontent.com/53487180/160829216-a0ab3511-71a5-40c6-9469-c03b15e29297.png)

He just show when the div have a space to show the entire select options:
![image](https://user-images.githubusercontent.com/53487180/160829594-5f2e410e-0bad-49e7-b70d-5b96604cdb0c.png)

**Comment by gnbm** [comment]
Hello.
I'm also having issues when using the dropdown, when in popup mode, inside Tabs (elements with overflow hidden). If the popup got for instance detached (like usually, a tooltip works for instance) this could be fixed.
Any plans to fix this behavior at least for the popup mode where this makes even more sense?
![InsideTabsOverflowHidden](https://user-images.githubusercontent.com/29493222/161324426-4a072b42-b489-4d94-9581-0cbafc8eff48.gif)

**Comment by sa-si-dev** [comment]
> When you open a select inside a div with overflow css property, this happend:
> ![image](https://user-images.githubusercontent.com/53487180/160829216-a0ab3511-71a5-40c6-9469-c03b15e29297.png)
> 
> He just show when the div have a space to show the entire select options:
> ![image](https://user-images.githubusercontent.com/53487180/160829594-5f2e410e-0bad-49e7-b70d-5b96604cdb0c.png)
> 

@guilhermerover set `dropboxWrapper: 'body'` property to solve your issue.

**Comment by sa-si-dev** [comment]
> Hello.
> I'm also having issues when using the dropdown, when in popup mode, inside Tabs (elements with overflow hidden). If the popup got for instance detached (like usually, a tooltip works for instance) this could be fixed.
> Any plans to fix this behavior at least for the popup mode where this makes even more sense?
> ![InsideTabsOverflowHidden](https://user-images.githubusercontent.com/29493222/161324426-4a072b42-b489-4d94-9581-0cbafc8eff48.gif)
> 
> 

@gnbm this feature already available, set `dropboxWrapper: 'body'` property to solve your issue.

**Comment by gnbm** [comment]
Thank you very much for the quick answer @sa-si-dev
