### ISSUE TITLE
About multi-Select for multi-level options

### ISSUE THREAD

**Issue by qingyuyu** [sa-si-dev/virtual-select#123]
I found that the setOptions method will update the value of the selection div. In a case where there are four multi-select div and I would like to update the remaining div options  according to the results from the server each time I choose an option. Is any possible that I can do that?

**Comment by sa-si-dev** [comment]
If I understood your requirement correctly, you have to call an ajax function on first drop-down change and on ajax success, call setOptions for other drop-downs.

**Comment by qingyuyu** [comment]
Exactly. Then any easy way to do that? One way I thought about was that I would have had a condition for each drop-downs before I setOptions for them.  What if makes some change on native code?

**Comment by sa-si-dev** [comment]
> Exactly. Then any easy way to do that? One way I thought about was that I would have had a condition for each drop-downs before I setOptions for them.  What if makes some change on native code?

What do you mean by "change on native code"?

**Comment by qingyuyu** [comment]
Maybe we could add a feature that user could select if they want reset the options list each time they call setOptions.

**Comment by sa-si-dev** [comment]
> Maybe we could add a feature that user could select if they want reset the options list each time they call setOptions.

Sorry, I am not getting your point here. The functionality of setOptions is to reset options list only.
