### ISSUE TITLE
Input/output ordering issues [issue #99 reopened]

### ISSUE THREAD

**Issue by GitHunter0** [sa-si-dev/virtual-select#125]
Hey @sa-si-dev , I think you did not see my follow up on #99 , so I took the liberty to reopen it here if that's ok.

The remaining issues are reported in this comment:
https://github.com/sa-si-dev/virtual-select/issues/99#issuecomment-1063313867

I would appreciate a lot if you can take a look on that.

**Comment by sa-si-dev** [comment]
@GitHunter0 I will check and fix those issues in the future release.

**Comment by GitHunter0** [comment]
Thanks a lot, @sa-si-dev

**Comment by sa-si-dev** [comment]
@GitHunter0 This issue has been fixed in the [release v1.0.28](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.28)

**Comment by GitHunter0** [comment]
@sa-si-dev , awesome! I will test it and give you feedback as soon as https://github.com/dreamRs/shinyvs update it
