### ISSUE TITLE
Misbehavior with dropboxWrapper: 'body' 

### ISSUE THREAD

**Issue by BenOsodrac** [sa-si-dev/virtual-select#126]
We tried to use the dropboxWrapper: 'body'  to fix some issues when the virtual-select was inside some elements with overflow. However, we found some issues with this option enable (tested with versions v1.0.26 and v1.0.27).

After selecting one of the options, it is no longer possible to close the dropbox:
https://i.imgur.com/i8oIGhm.gif

It seems that it's removing the class 'pop-comp-active' when it shouldn't and this is used to validate if it should close the dropbox or not (image below).
![image](https://user-images.githubusercontent.com/32780808/162440946-82942bd7-d573-4580-99c5-fa5331d6144b.png)

Also, with this option, in Chrome sometimes the text gets really blurred:
![image](https://user-images.githubusercontent.com/32780808/162441116-5823f2ad-4bac-4cf0-8ebc-9b84cdc682d6.png)

Let me know if there's more info you need from me!

Thanks for your work!

**Comment by sa-si-dev** [comment]
@BenOsodrac I will check and fix it in the future release.

**Comment by sa-si-dev** [comment]
@BenOsodrac It is working for me.

Please share error message, if there is any in the console.

Try examples in the plugin [documentation] (https://sa-si-dev.github.io/virtual-select/#/examples?id=show-values-as-tags).
Let me know if you get same behaviour there.

**Comment by BenOsodrac** [comment]
Hi @sa-si-dev,

Thanks for the feedback. 

I have no errors on console on this, just runtime misbehaviors. I checked your demos and in fact it seems to be working there!

I will try to have a screen as clean as possible where this issue happens and share it with you!

Thanks,
Bernardo

**Comment by BenOsodrac** [comment]
Hi @sa-si-dev, here's the link with the issue:

**Comment by sa-si-dev** [comment]
> Hi @sa-si-dev, here's the link with the issue:
> https://abgc.outsystemscloud.com/VirtualSelect/VirtualSelectBody
> 
> 1. Open dropdown
> 2. Select an option
> 3. Try to close the dropdown

I will check it.

**Comment by sa-si-dev** [comment]
@BenOsodrac This issue has been fixed in the [release v1.0.28](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.28)

**Comment by BenOsodrac** [comment]
@sa-si-dev Awesome!

Thanks for your work, 
Bernardo
