### ISSUE TITLE
How can we load the docs locally for easier debugging & testing?

### ISSUE THREAD

**Issue by frg** [sa-si-dev/virtual-select#13]
Hi, currently I'm using a sample page I created to be able to test and debug changes. Is it possible to load the docs locally? If so, how? It looks like Jekyll is being used but I have no experience with this library.

Maybe if loading the docs is possible locally, can we have a setup with package.json to be able to easily load them?

Thanks

**Comment by sa-si-dev** [comment]
1. Install docsify globally

    `npm i docsify-cli -g`

2. Run below command from your project root folder to start localhost

    `docsify serve docs`

**Comment by frg** [comment]
@sa-si-dev Would you be open to the idea of making a pr to include this as part of `package.json` and adding this to the `README.md`?

```json
{
  ...
  "scripts": {
    "docs": "docsify serve docs",
    ...
  },
  ...
  "devDependencies": {
    ...
    "docsify-cli": "^4.4.2",
    ...
  }
}
```

**Comment by sa-si-dev** [comment]
I was planned to add it in next release. I will add it.

**Comment by frg** [comment]
I have the branch ready with this change if you'd like @sa-si-dev 🙂

**Comment by sa-si-dev** [comment]
Sure, send a request.

**Comment by frg** [comment]
Pr open #14
