### ISSUE TITLE
Virtual-select from a native select element, that has an empty value selected, shows values as a comma-separated list

### ISSUE THREAD

**Issue by krispern** [sa-si-dev/virtual-select#135]
Virtual-select from a native select element, that has an empty value selected, shows values as a comma-separated list. This is true even when the multiselect is `false`.

Steps to repeat:
1. Create a `<select>` with some options
2. Initialise the VirtualSelect component
3. Select any option from the list
4. Value displayed in the field starts with a comma

Codepen: https://codepen.io/krispern/details/BaJbYvp

**Comment by sa-si-dev** [comment]
@krispern I will fix this issue in the future release. Thanks for letting me know it.

**Comment by sa-si-dev** [comment]
@krispern This issue has been fixed in the [release v1.0.29](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.29).
