### ISSUE TITLE
`<optgroup>` from native select element isn't converted to the virtual-select

### ISSUE THREAD

**Issue by krispern** [sa-si-dev/virtual-select#136]
`<optgroup>` from native select element isn't converted to the virtual-select

Steps to repeat:
1. Create a <select> with an `<optgroup>` element and some options
2. Initialise the VirtualSelect component
3. The options are shown, but the optgroup value is not

Codepen: https://codepen.io/krispern/pen/MWrxBzM

**Comment by sa-si-dev** [comment]
@krispern This feature has been implemented in the [release v1.0.29](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.29).
