### ISSUE TITLE
Easy init for options

### ISSUE THREAD

**Issue by ahsynv** [sa-si-dev/virtual-select#137]
Hi,

Actually, to add some options, we do something like this:

` options: [
            {
                "label":"test1",
                "value":"test1"
            },
            {
                "label":"test2",
                "value":"test2"
            },
            {
                "label":"test3",
                "value":"test3"
            },
....
        ],`

As you can see, the "labels" and "values" are the same, so sometimes the "label" key is not useful, if we dont add it, we dont see the options. Is it possible to add a condition, to check if the label is set or not, if not, show the "value" on front end, instead of empty values?

And also, can you please accept an array of simple values instead of objects? For example, convert our example above to this

` options: [ "test1", "test2", "test3" ]`

As this way, we can write only 1 lines of the code when we dont need to specifiy the "label" which is the same

**Comment by sa-si-dev** [comment]
@ahsynv For first structure, you could set `labelKey: 'value'` to use value property for both label and value.

For second structure, I will implement it in the future release.

Thanks for the suggestion.

**Comment by sa-si-dev** [comment]
@ahsynv I have added a feature to init with an array of strings as options.

This feature is available in the [release v1.0.30](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.30)
