### ISSUE TITLE
Minimum options 

### ISSUE THREAD

**Issue by ahsynv** [sa-si-dev/virtual-select#139]
Hi,

Do we have an option to define a minimum options?

Like this feature: https://sa-si-dev.github.io/virtual-select/#/examples?id=maximum-values
But for exemple if we have 5 options and minimum 2 options are required, disable "uncheck" for last selected values.

Thanks

**Comment by sa-si-dev** [comment]
Okay. I will implement it in the future release.

Thanks for the suggestion and explanation.

**Comment by sa-si-dev** [comment]
@ahsynv I have added a new property `minValues` which would be used with the required validation.

This feature available in the release [v1.0.32](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.32)
