### ISSUE TITLE
additionalClasses not being applied

### ISSUE THREAD

**Issue by warmwhisky** [sa-si-dev/virtual-select#141]
When I use the property `additionalClasses` they are being applied before the plugins classes and do not get applied.

I would like to style the input the same way I my own inputs using tailwind.

Any idea what I am doing wrong or misunderstanding here?

Here is my current VirtualSelect.init
```
VirtualSelect.init({
    ele: '#sample-select',
    allowNewOption: true,
    additionalClasses: 'border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 rounded-md shadow-sm block mt-1 w-full mb-3',
    options: [
        { label: 'Options 1', value: '1' },
        { label: 'Options 2', value: '2' },
        { label: 'Options 3', value: '3' },
    ],
});
```

**Comment by sa-si-dev** [comment]
@warmwhisky `additionalClasses` would be added with container element.

To customize the drop-down button, add styles to `.vscomp-toggle-button` element.

**Comment by warmwhisky** [comment]
@sa-si-dev Thank you. That's got it for me :)
