### ISSUE TITLE
Customize width

### ISSUE THREAD

**Issue by mai1237** [sa-si-dev/virtual-select#142]
Is there a way to customize the width of the object?

**Comment by sa-si-dev** [comment]
> Is there a way to customize the width of the object? 

What do you mean by "width of the object"?

**Comment by mai1237** [comment]
the <select class="w-full"> does not working in tailwind

**Comment by sa-si-dev** [comment]
> the <select class="w-full"> does not working in tailwind 

@mai1237 sorry. I couldn't understand your question.

**Comment by bes-internal** [comment]
@mai1237 Width set to 100% and default max-width set to 250px. You can customize max-width with `maxWidth` property starting from v1.0.28
