### ISSUE TITLE
Dropdown content text got blurred

### ISSUE THREAD

**Issue by gnbm** [sa-si-dev/virtual-select#143]
Hello.
I updated the library to version 1.0.29 (I was using 1.0.27) and on several screen resolutions I started having a major visual breaking change where the text inside the dropdown when opened gets blurred as you can see:
 
![textBlurred2](https://user-images.githubusercontent.com/29493222/167826307-9bf8f8d1-dd44-4a05-b4f0-c0674ff0b3b6.png)

It seems to be something related to an inline style that is added with a translate3d.
I add to rollback this version so, if we could have a fix for this it would be great.
Thank you!

**Comment by sa-si-dev** [comment]
Please share your page URL.

**Comment by gnbm** [comment]
> Please share your page URL.

This is a page from an internal infrastructure that you won't be able to access. I'll try to replicate on a codepen

**Comment by jmakoni** [comment]
> Hello. I updated the library to version 1.0.29 (I was using 1.0.27) and on several screen resolutions I started having a major visual breaking change where the text inside the dropdown when opened gets blurred as you can see:
> 
> ![textBlurred2](https://user-images.githubusercontent.com/29493222/167826307-9bf8f8d1-dd44-4a05-b4f0-c0674ff0b3b6.png)
> 
> It seems to be something related to an inline style that is added with a translate3d. I add to rollback this version so, if we could have a fix for this it would be great. Thank you!

Hi gnbm,

How did you customise to get that look and feel?

**Comment by gnbm** [comment]
> > Hello. I updated the library to version 1.0.29 (I was using 1.0.27) and on several screen resolutions I started having a major visual breaking change where the text inside the dropdown when opened gets blurred as you can see:
> > ![textBlurred2](https://user-images.githubusercontent.com/29493222/167826307-9bf8f8d1-dd44-4a05-b4f0-c0674ff0b3b6.png)
> > It seems to be something related to an inline style that is added with a translate3d. I add to rollback this version so, if we could have a fix for this it would be great. Thank you!
> 
> Hi gnbm,
> 
> How did you customise to get that look and feel?

Not sure I got the question, but it's custom CSS on top of the virtual select styles like we usually do on frontend work

**Comment by gnbm** [comment]
@sa-si-dev I updated to the latest version 1.0.30 and I still get this issue.
You can find a sample on [this page](https://personal-63r2lngs.outsystemscloud.com/VirtualSelectIssues/DropdownSearch)
This provides a really poor experience in terms of UI to the customers so once again we'll postpone the upgrade. Thank you

**Comment by gnbm** [comment]
@sa-si-dev Were you able to reproduce the issue I reported? At least I can reproduce 100% of time? Tested in Chrome, Firefox and Edge

**Comment by gnbm** [comment]
@sa-si-dev You can replicate it depending on the screen resolution it seems. I have a laptop connected to a wide screen monitor and on the monitor, it doesn't happen but on my laptop it does. 
Example:
![ImageInfo](https://user-images.githubusercontent.com/29493222/176188376-76365dee-d53e-4a6e-af4f-3bfc5bc230ce.PNG)

**Comment by gnbm** [comment]
@sa-si-dev Were you able to replicate it with the last information I provided? Thank you in advance

**Comment by sa-si-dev** [comment]
@gnbm it seems it is working fine in my machine.

Could you please share your browser version and OS name.

**Comment by gnbm** [comment]
@gnbm I'm using Windows 10 Enterprise and I can replicate it 100% of times in:
- Chrome (currently, Version 103.0.5060.66 (Official Build) (64-bit) but I update it all the time)
- Edge (currently, Version 103.0.1264.44 (Official Build) (64-bit))
In Firefox I can't replicate it all the time

**Comment by joselrio** [comment]
Hi @sa-si-dev,
I'm able to reproduce this behaviour 100% the times...

Using **MacOS**, and here's the feedback:
- ❌ **Chrome** - **gets blurry** => Version 103.0.5060.53 (Official Build) (arm64)
- ❌ **Safari Technology Preview** - **gets blurry** => Release 139 (Safari 15.4, WebKit 17613.1.14.41.3)
- ✅ **Firefox** - **Working as expected** => 101.0.1 (64-bit)

**Comment by bmarcelino-fe** [comment]
Hi @sa-si-dev,

On our project we have the same behaviors, the blurred text on dropdown appears in different browsers. You can check it using the example on your [website](https://sa-si-dev.github.io/virtual-select/#/?id=get-started).

- ❌ Safari
- ❌ Safari Technology Preview
- ❌ Chrome

The browsers has the latest versions and i'm using MacOS.

**Comment by sa-si-dev** [comment]
> Hi @sa-si-dev,
> 
> On our project we have the same behaviors, the blurred text on dropdown appears in different browsers. You can check it using the example on your [website](https://sa-si-dev.github.io/virtual-select/#/?id=get-started).
> 
> - ❌ Safari
> - ❌ Safari Technology Preview
> - ❌ Chrome
> 
> The browsers has the latest versions and i'm using MacOS.
> 

I will check again.

**Comment by gnbm** [comment]
@sa-si-dev It seems to be something related to an inline style that is added with translate3d but not 100% sure.

**Comment by sa-si-dev** [comment]
@gnbm, it is working fine for me. I tried in Mac OS - Chrome Version 103.0.5060.114

https://user-images.githubusercontent.com/76465932/179406055-a1ca50e7-6b63-4861-ba0a-412400b2bc01.mov

**Comment by gnbm** [comment]
@sa-si-dev This is really strange and it seems I'm not the only one having the same issue that would have a really bad experience on end users. I just retested it without connecting to an external monitor and I'm on a Dell using Windows with this resolution:
![image](https://user-images.githubusercontent.com/29493222/179425962-5260e9e9-dac6-4957-b55f-b7e43e1e9698.png)

Using Chrome:
![DropdownsBlurryChrome](https://user-images.githubusercontent.com/29493222/179425974-ef1b73de-8694-4714-b520-1ca2bdbc119f.gif)

Using Edge:
![DropdownsBlurryEdge](https://user-images.githubusercontent.com/29493222/179425979-eb34c9e9-bee8-491b-bacc-df608123f7b3.gif)

Also, the dimensions and ratio:
![image](https://user-images.githubusercontent.com/29493222/179426200-2e449814-56f1-4683-9241-b3078c966628.png)

**Comment by gnbm** [comment]
@sa-si-dev Just did a quick test updating to the latest 1.0.31 and it seems that something changed and this behaviour was improved somehow. I'll run more tests along the week and will keep you posted.
Meanwhile, @joselrio @bmarcelino-fe @BenOsodrac could you also test this on your end? It would be great to have more feedback on this.

**Comment by gnbm** [comment]
After updating to the latest 1.0.31 I was no longer able to reproduce the issue, so will close this issue.
