### ISSUE TITLE
Select only the results of the search

### ISSUE THREAD

**Issue by freddidierRTE** [sa-si-dev/virtual-select#148]
When you make a search :

![image](https://user-images.githubusercontent.com/58251627/169849561-689d4bdf-78da-4c23-8e8b-9569f8e7321b.png)

If you click on the checkbox on the left of the search it should select only the result of the search and not all the options :

![image](https://user-images.githubusercontent.com/58251627/169849794-199f7424-8cc5-4187-a280-c70eec59e6df.png)

**Comment by sa-si-dev** [comment]
@freddidierRTE set `selectAllOnlyVisible: true` to enable this feature.

**Comment by freddidierRTE** [comment]
It works , thanks !
