### ISSUE TITLE
 Option SelectAllOnlyVisible set to true , can not unselect all visible 

### ISSUE THREAD

**Issue by freddidierRTE** [sa-si-dev/virtual-select#151]
selectAllOnlyVisible set to true , when select all visible after search :

![image](https://user-images.githubusercontent.com/58251627/171028277-6a5b3310-e8fd-4640-bb71-6466bb178d19.png)

The checkbox for all is not selected  (FR on the screenshot ) and you can not unselect

**Comment by sa-si-dev** [comment]
@freddidierRTE this is expected behaviour only. Here not all options are selected, if you clear the search text, there would be some unselected options.

**Comment by freddidierRTE** [comment]
ok , so i may ask if it is possible to change the behavior ?

The idea would be  , if selectAllOnlyVisible is set to true : 

- The checkbox is selected if all visible options are selected 
- If we click on the checkbox when unselected , all visible options become selected 
- If we click on the checkbox when selected , all visible options become unselected 

The actions on the selectAll chechbox would not affect unvisible values. It means the user can select first a list of value based on a  search  and then search other values and add them to the previously selected one (that is not possible today , the selected values of the first search are replace by the selected values of the second search) 

The wanted behavior is based on the way  the  check-box "Select all filtered results"  of   angular2-multiselect-dropdown works :  https://cuppalabs.github.io/angular2-multiselect-dropdown/#/searchfilterAddNewItem 

 ( In our projet, we were using this angular component previously , we are using now VirtualSelect as we want a mutliselect independant of angular)

**Comment by sa-si-dev** [comment]
Thanks for the suggestion. I will implement it in the future release.

**Comment by sa-si-dev** [comment]
@freddidierRTE this feature has been implemented in the [release v1.0.36](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.36)
