### ISSUE TITLE
Mouse scroll doesn't work properly

### ISSUE THREAD

**Issue by krispern** [sa-si-dev/virtual-select#152]
Steps to recreate (also happens on the Get Started page demo fields):
1. Open the dropdown
2. Hover over the open list and try to scroll with the mouse middle button
3. Works once, not after that until you move the mouse.

Works fine when hovering over the dropdown's scrollbar

**Comment by sa-si-dev** [comment]
It is working as expected for me.

May I know which OS and browser you are using.

**Comment by krispern** [comment]
I'm on Windows 10, Google Chrome Version 102.0.5005.62 (Official Build) (64-bit). Tried turning off all extensions, no change, still gets stuck after the first scroll.

Tested other browsers:
Works correctly on Firefox, Opera, Vivaldi, Edge. IE didn't load the demo page

**Comment by IcyFrogs** [comment]
Me too. It was working perfectly fine up until a few days ago.

**Comment by IcyFrogs** [comment]
I don't think this issue exists anymore. Resolved with the latest chrome browser.
Thanks

**Comment by krispern** [comment]
Yes, it's no longer getting "stuck".
