### ISSUE TITLE
Dropdown scroll with wheel mouse is very very slow

### ISSUE THREAD

**Issue by shaangidwani** [sa-si-dev/virtual-select#153]
Dropdown scroll with wheel mouse is very very slow.

When user try to scroll with wheel mouse its moving very slow. 2-3 records per scroll. 

It should very very smooth like standard dropdown  with 10 records.

**Comment by sa-si-dev** [comment]
@shaangidwani I will check and fix it in the future release.

Thanks for letting me know it.

**Comment by sa-si-dev** [comment]
As per the comment from an another [issue](https://github.com/sa-si-dev/virtual-select/issues/152#issuecomment-1177203754), this issue is not exist anymore.

@shaangidwani Please try again
