### ISSUE TITLE
Detached ballon flickering when scrolling 

### ISSUE THREAD

**Issue by gnbm** [sa-si-dev/virtual-select#156]
Hello.
I updated the library to version 1.0.30 (I was using 1.0.27) to take advantage of an issue that was reported to be fixed (#144) but got another issue. Basically, when we have dropboxWrapper='body' and we are scrolling with the detached ballon, the animation is not fluid and we get a flickering. Probably using a requestAnimationFrame() would do the trick but I was not able to try it out

![DropdownDettached](https://user-images.githubusercontent.com/29493222/176021470-c5d54b63-bdcc-4c97-9d26-929efa07edf6.gif)

Keep up the great work on this amazing component that is getting better and better!!

**Comment by sa-si-dev** [comment]
I have throttle time of 100ms for scroll event. I will give a property to configure it in the future release.

**Comment by sa-si-dev** [comment]
@gnbm this issue has been fixed in the [release v1.0.31](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.31)

**Comment by gnbm** [comment]
Awesome @sa-si-dev 
Thank you for the feedback and once again great work on this component 🚀
