### ISSUE TITLE
Trigger Search does not occur when paste using mouse.

### ISSUE THREAD

**Issue by joselrio** [sa-si-dev/virtual-select#157]
Hi there,

When user uses mouse to paste text inside search input, the search (onSearch) does not occur.

After looking into library code, you're missing the **cut** and **paste** event at the search input that also should trigger it ;) 

Thanks in advance!
JR

**Comment by sa-si-dev** [comment]
@joselrio thanks for letting me know this issue. I will fix it in the future release.

**Comment by sa-si-dev** [comment]
this issue has been fixed in the [release v1.0.31](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.31)
