### ISSUE TITLE
WindowResize issue

### ISSUE THREAD

**Issue by joselrio** [sa-si-dev/virtual-select#171]
Hi @sa-si-dev,

Found another issue after updating to the latest version (on the scope of https://github.com/sa-si-dev/virtual-select/issues/169) that is related with the window resize, when a resize occurs the dropdown balloon is not following the input.

Thanks for your work!
Cheers,
JR

**Comment by sa-si-dev** [comment]
@joselrio I will check and fix it in the future release.

Thanks for letting me know it.

**Comment by sa-si-dev** [comment]
@joselrio This issue has been fixed in the release [v1.0.32](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.32)
