### ISSUE TITLE
How can i remove all options from select?

### ISSUE THREAD

**Issue by YahyaAltintop** [sa-si-dev/virtual-select#172]
I use `setOptions()` method without any parameter but it's not rendering. When i scroll into option list, it's rendering.

I tried use `reset()`  `setOptions()` `renderOptions()` methods at the same time, like this

![Screenshot 2022-08-19 182701](https://user-images.githubusercontent.com/69236857/185653471-9b3c7947-ee8e-418e-94ca-c8438700f3f7.png)

But after 2 calls it throws error

![image](https://user-images.githubusercontent.com/69236857/185654406-5f9e65e6-cbbd-494e-ab98-a9b81c368288.png)

I think there should be a `clearOptions()` method and it remove all options from select in this way select value is empty.

**Comment by sa-si-dev** [comment]
You should call set options method with DOM instance as below.

https://sa-si-dev.github.io/virtual-select/#/methods?id=setoptions

**Comment by YahyaAltintop** [comment]
But it's not rendering options. When I scroll in the options div, it's render select.

https://user-images.githubusercontent.com/69236857/185776411-79ea5318-986a-4fcb-ab53-175f18c765a0.mp4

**Comment by sa-si-dev** [comment]
May I know, how do you call `setOptions` method?

What is `fleetBranchSelect` here?

**Comment by YahyaAltintop** [comment]
Sorry. I'm wrong here
