### ISSUE TITLE
Wrong behavior when your selecting all searched ones in list

### ISSUE THREAD

**Issue by AliBigdeli** [sa-si-dev/virtual-select#176]
I was trying to add a functionality with the default settings you already provided and there was one thing bothering me, when I have already a few selected ones in list and I start to search, there will be some results for example, as soon as I hit select all it will overwrite the existing selection instead of adding it and only visible ones are now selected and my older selected ones are gone.
i don't know if this is a bug or not but its awkward t do it like that.

this was my configuration:
VirtualSelect.init({
                    ele: '#job-title-list-filter',
                    options: job_title_options,
                    multiple: true,
                    search: true,
                    showSelectedOptionsFirst: true,                    
                    markSearchResults:true,
                    selectAllOnlyVisible:true,
                });

pre-selected ones:
![image](https://user-images.githubusercontent.com/29748439/187878228-842a7532-7100-4a92-9099-1857bd823ac7.png)

selected all the ones are visible
![image](https://user-images.githubusercontent.com/29748439/187878445-6042cf3a-bb2e-425e-802e-6f1c7f736546.png)

and now previous ones are gone

**Comment by sa-si-dev** [comment]
@AliBigdeli this is the expected behaviour as of now. I will find a way to handle your case and implement it.

**Comment by AliBigdeli** [comment]
Thanks i appreciate  it, and also thank you for the awsome module you provided 👍

**Comment by freddidierRTE** [comment]
linked  with  #151

**Comment by sa-si-dev** [comment]
@AliBigdeli this feature has been implemented in the [release v1.0.36](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.36)
