### ISSUE TITLE
[Bug] Textbox value getting reset when allowNewOption and onServerSearch enabled

### ISSUE THREAD

**Issue by SahajJain01** [sa-si-dev/virtual-select#177]
When both properties (allowNewOption and onServerSearch) is enabled,

After typing a search value for which the function bound to onServerSearch doesn't return any results, the option to add new option comes with the + symbol.

On clicking this option, the function bound to onServerSearch gets called again with an empty string param which causes the field to get reset since server returns no result and setServerOptions() gets called with blank data.

Workaround is to put a return in function bound to onServerSearch like this
if(searchValue == "") {return;}
but this causes the dropdown to show an infinite loading symbol when you clear the search text.

Ideally, on selecting newly added option, the search function should not be called in the first place.
If I get time I will try to find a fix and create pull request :)

**Comment by sa-si-dev** [comment]
@SahajJain01 This issue has been fixed in the release [v1.0.32](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.32)

**Comment by yahyaerturan** [comment]
I am facing this same issue, clicking on a search result triggers search with an empty term. This issue should be fixed on 1.0.32.. However, 1.0.32 and 1.0.33 i think it is somehow mis-built. As I understand from merged PR, a new `isClearingSearchValue` introduced to fix this issue. But in versioned js file, these changes are missing.  Can you check please? @sa-si-dev @caiosm1005

**Comment by yahyaerturan** [comment]
Should I open a new issue for this? @sa-si-dev
