### ISSUE TITLE
Select with info

### ISSUE THREAD

**Issue by markteunen65** [sa-si-dev/virtual-select#18]
![listbox with info](https://user-images.githubusercontent.com/32696786/107139589-a9944780-691c-11eb-92e6-5b34f12d1414.png)

It would be very nice if one could have an additional options[].info where one could define extra info (see attachment).
Or I suppose you could use the options[].alias property and have an additional option (showAlias or something)

Very nice code, by the way :)

**Comment by sa-si-dev** [comment]
@markteunen65 Thank you for your suggestion. I will work on it in the future release.

**Comment by sa-si-dev** [comment]
@markteunen65 as you requested, I have implemented this feature and it is available in the [release v.1.0.5](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.5)
