### ISSUE TITLE
Show all options selected

### ISSUE THREAD

**Issue by chathu020** [sa-si-dev/virtual-select#187]
### Discussed in https://github.com/sa-si-dev/virtual-select/discussions/186

<div type='discussions-op-text'>

<sup>Originally posted by **chathu020** September 29, 2022</sup>
In multiple selection is it possible to show all selected options names without showing as 'X options selected' ?</div>

**Comment by sa-si-dev** [comment]
@chathu020 I will implement this feature in the future release.

**Comment by nightrider77** [comment]
Hm, I thought it was already implemented, demo page was showing it like @chathu020 described:
https://www.cssscript.com/demo/select-box-virtual-scroll/

**Comment by sa-si-dev** [comment]
> Hm, I thought it was already implemented, demo page was showing it like @chathu020 described:
> https://www.cssscript.com/demo/select-box-virtual-scroll/

@nightrider77 that page has first version of plugin only.

Refer [https://sa-si-dev.github.io/virtual-select](https://sa-si-dev.github.io/virtual-select) for the latest version.


In the latest version, if there is no space to show selected option's label, no.of selected option's count would be displayed.

**Comment by sa-si-dev** [comment]
@chathu020 this feature has been implemented in the [release v1.0.36](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.36)

Set `alwaysShowSelectedOptionsLabel: true` to show selected option's names instead of `X options selected`
