### ISSUE TITLE
Optgroup & showSelectedOptionsFirst issue

### ISSUE THREAD

**Issue by ahsynv** [sa-si-dev/virtual-select#19]
Hi,

When we are using Optgroup feature and activate the "showSelectedOptionsFirst", its not working, all selected options have the same order 😕

Is it possible to do something like : 

1. If any child of the optgroup is selected, change the order of this one and show it first ?
2. Or show all selected items first without any optgroup ( and keeping other optgroups with childs )

You have many possibilities, I can't put everything here but you surely have a better idea, thanks in advance !

**Comment by sa-si-dev** [comment]
I will implement it in the future release.

**Comment by sa-si-dev** [comment]
@ahsynv as you requested, I have enabled showSelectedOptionsFirst feature for optGroup

This feature and it is available in the [release v.1.0.5](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.5)
