### ISSUE TITLE
Improvement for DOM selects with options that start with value 0

### ISSUE THREAD

**Issue by squareclouds** [sa-si-dev/virtual-select#192]
hi everyone,

i was having trouble when creating virtual-selects from already populated selects. for my cms it is a lot easier in the data handling if the values start with 0. this was creating problems though, since when no value was selected and my values started with 0, the first element was always getting set. for this i suggest this modification in the code. i just check if the selected **attribute** of the option is indeed set, since $option.selected was unreliable when starting the values with 0.

i hope this helps someone else!

line 3580:

```
if ($option.getAttribute('selected') =='') {            
   selectedValue.push(value);           
}
```

**Comment by sa-si-dev** [comment]
@squareclouds Could you please share a sample code to reproduce this issue?

**Comment by squareclouds** [comment]
@sa-si-dev its been a few weeks, so not right away. but what i mean is if my options look like this in html. since the first value value is 0, the value was always getting set even though in HTML it was not set as shown here in the example.


<select name="years" id="years">
  <option value="0">New</option>
  <option value="1">1 year</option>
  <option value="2">2 years</option>
  <option value="3">3 years</option>
</select>

**Comment by sa-si-dev** [comment]
> @sa-si-dev its been a few weeks, so not right away. but what i mean is if my options look like this in html. since the first value value is 0, the value was always getting set even though in HTML it was not set as shown here in the example.
> 
> 
> <select name="years" id="years">
>   <option value="0">New</option>
>   <option value="1">1 year</option>
>   <option value="2">2 years</option>
>   <option value="3">3 years</option>
> </select>

Are you saying first option is auto selected when initialising from native select element?

If so, that is expected behaviour only. Because in native select, first value would auto selected. So I doing the same.

**Comment by squareclouds** [comment]
ah ok, then it works as intended i think. i changed my code a bit to solve my specific problem
