### ISSUE TITLE
Dropdown not working in table column

### ISSUE THREAD

**Issue by pareshswipez** [sa-si-dev/virtual-select#193]
I am trying to add multiple dropdowns in table but it is not working, dropdown options are hiding in a table cell. 

![U9hgsPdalU](https://user-images.githubusercontent.com/54345650/196395851-864ee092-b7c8-4ea4-9b55-d055a7c1cad1.gif)

**Comment by sa-si-dev** [comment]
@pareshswipez Please use `dropboxWrapper: 'body'` property to avoid this issue.
