### ISSUE TITLE
It's selected as if it's on the screen.

### ISSUE THREAD

**Issue by feents** [sa-si-dev/virtual-select#195]
https://jsfiddle.net/u6ezwvjt/

1. click to select box
2. input "test" in search text
3. click to checkbox for search text
4. click to html body
![vs-1](https://user-images.githubusercontent.com/67404954/196903602-769b5217-f8aa-4fab-aa5f-ed5f00ed7eec.png)
(At 4 step, something moves on the screen)

5. click to clear btn
![vs-2](https://user-images.githubusercontent.com/67404954/196904336-c1b3c906-ef4d-425e-8798-522e87ed34e2.png)

6. click to select box down side
![vs-3](https://user-images.githubusercontent.com/67404954/196905153-e49e03ff-53c9-4531-add7-4ec581932021.png)

error
It's selected as if it's on the screen.

**Comment by sa-si-dev** [comment]
@feents thanks for letting me know this issue. I will fix it in the future release.

**Comment by sa-si-dev** [comment]
@feents this issue has been fixed in the [release v1.0.34](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.34)
