### ISSUE TITLE
BUG: Create a multiselect from DOM elements with Optgroup

### ISSUE THREAD

**Issue by squareclouds** [sa-si-dev/virtual-select#197]
hello,

it seems there is a bug when:

- i initialize virtual-select from a `<select multiple>`
- the select has at least one `<optgroup>`
- the optgroup is not the first item

then something strange happens. when i click the first item, it does not get selected

![grafik](https://user-images.githubusercontent.com/9073054/198074779-eda800de-6d0d-4bd9-b7d2-995dcd60e968.png)

but if i check the hidden input, it keeps filling up everytime i keep clicking on the item!

![grafik](https://user-images.githubusercontent.com/9073054/198074887-dd194730-59d4-433e-9d63-494a531b1afe.png)

the DIV option itself does not changes status to "selected" nor aria-selected="true", like the others

![grafik](https://user-images.githubusercontent.com/9073054/198075085-5f7ccba9-f0f0-46bb-9040-0acdcf37244c.png)

any help is appreciated!!!!

EDIT:

I just realized if two options are at the beginning, lets say

```
<option>
<option>
<optgroup>
      <option>
      <option>
```
and i select the second one, the first also gets selected!

**Comment by sa-si-dev** [comment]
@squareclouds This issue has been fixed in the [release v1.0.35](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.35)

**Comment by squareclouds** [comment]
yes thank you! i found it out a bit later :)
