### ISSUE TITLE
Selecting an option triggers onServerSearch and breaks the plugin

### ISSUE THREAD

**Issue by yahyaerturan** [sa-si-dev/virtual-select#199]
I have shared my settings down there. When I search, results shown, but when I select, for a second I see my clicked option selected but after text changes to placeholder text, yet close button stands. Same time it triggers `onServerSearch`'s ajax funtion without a term. Also after, when I open dropdown again, it has options inside but labels are not shown. Things are really messed up here. 

In search box, if I type fast i can search what I want. But if I press "a" and wait, it triggers search with "a" term, however after clears term to nothing. Yet search results stays.

```javascript
let settings = {
  name: "my_input_name",
  ele: "#myDropdown",
  dropboxWrapper: "body",
  labelKey: "name",
  valueKey: "id",
  search: true,
  markSearchResults: true,
  placeholder: "Type to select",
  searchPlaceholderText: "Search ...",
  noSearchResultsText: "No result found",
  onServerSearch: function (searchValue, virtualSelect) {
      if (typeof searchValue !== "undefined" || searchValue !== "") {
        $.ajax({
            url: searchUrl+"?term="+searchValue,
            method: "GET",
        }).done(function (fetchedOptions) {
            virtualSelect.setServerOptions(fetchedOptions);
        });
      }
  },
}

let selectVS = VirtualSelect.init(settings);
```

**Comment by sa-si-dev** [comment]
@yahyaerturan I will check and fix it. Thanks for letting me know it.

**Comment by sa-si-dev** [comment]
@yahyaerturan Please check this issue in the latest version and let me know if this issue still exists or not.

**Comment by gnbm** [comment]
@yahyaerturan any update on this? Can you replicate it with the latest version?

**Comment by yahyaerturan** [comment]
I have checked it on Nov 30. It doesn't help. It was a live project so I had to write a new library and remove the virtualSelect. That's why if newer versions fixed it or not, I don't know :( Sorry.
