### ISSUE TITLE
Event when item was selected

### ISSUE THREAD

**Issue by xtance** [sa-si-dev/virtual-select#2]
Hello!
Is there a possibility to fire an event when an item was chosen by user?

Also, thanks a lot for this awesome library. It is really helpful for CEF versions without <select> tag support.

**Comment by sa-si-dev** [comment]
Thanks for your feedback.

> You can use 'change' event listener. It would be triggered when user choose item.


```js
/** in vanilla javascript */
document.querySelector('#sample-select').addEventListener('change', function() {
  console.log(this.value);
});

/** in jquery */
$('#sample-select').change(function() {
  console.log(this.value);
});
```

**Comment by xtance** [comment]
Nice to know that, thanks a lot :з
