### ISSUE TITLE
Creating a hidden input by default to save selected data

### ISSUE THREAD

**Issue by ahsynv** [sa-si-dev/virtual-select#20]
Hi, for the moment, we are using some custom solution to send the selected data. Actually we have an event listener to listen the selectbox, when its changed, we are creating a virtual input with a custom "name" attribute and change its value.

Is is possible to add a new parameter like "createVirtualInput" and "createVirtualInputName" and when first one is true, the virtual-select class create a virtual input with a "name" attr = "createVirtualInputName". It will be really useful and allow us to have a clean code ! Thanks a lot, when i will have free time i will try to do some PR to help you 😊

**Comment by sa-si-dev** [comment]
If I understood your requirement correctly, I think we have already support native `change` event listener. Please check below docs page

https://sa-si-dev.github.io/virtual-select/#/events

Please check it and let me know, if it dosen't fulfill your requirement.

**Comment by ahsynv** [comment]
Hi, thank you for reply ! No my issue is not about the event listener. So i will try to explain on another way : 

With the native html "select" element, we have "name" attribute, like this : 

```
<form action="blabla" method="POST">
<select name="country">
<option value="FR">France</option>
<option value="ES">Spain</option>
</select>
</form>
```

On this example, when we select an option like "Spain" and click on submit button, on the back end for example PHP i can get the selected value by $_POST['country'], but on virtual-select, i dont found this fonctionnality, how we can get the selected value outside of js ?

**Comment by sa-si-dev** [comment]
@ahsynv I got your requirement. I will implement it in the future release.

**Comment by sa-si-dev** [comment]
@ahsynv as you requested, I have implemented this feature and it is available in the [release v.1.0.4](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.4)
