### ISSUE TITLE
Get disabled options

### ISSUE THREAD

**Issue by squareclouds** [sa-si-dev/virtual-select#200]
hello and thanks for this really cool tool. somehow the functionality to retrieve the disabled values is missing, though, and i cant find a workaorund. is there an easy way to get to the variable?

**Comment by sa-si-dev** [comment]
@squareclouds May I know why do you want to get disabled values?

**Comment by squareclouds** [comment]
@sa-si-dev of course. i was creating a sync logic between virtual-selects. so if you select something in one of them, you disable that one option in the other ones. its been a couple of days to give you a more detailed info, but that was the core idea of it. and since i dont create the options via JS but directly as HTML (PHP) and only initialize the selects via JS it would be easier to know which values are disabled in each one of them.

**Comment by sa-si-dev** [comment]
@squareclouds this feature has been implemented in the [release v1.0.36](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.36)

Use [getDisabledOptions()](https://sa-si-dev.github.io/virtual-select/#/methods?id=getdisabledoptions) method

**Comment by squareclouds** [comment]
perfect, thank you for this
