### ISSUE TITLE
When onServerSearch is enabled, there is no way to make a way to avoid many requests

### ISSUE THREAD

**Issue by stefchrif** [sa-si-dev/virtual-select#203]
Hi,

When **onServerSearch** is enabled, there is no way to make the function wait for example few ms to not make many requests while the user is typing, nor a minimum number of char to fire the search.

For example to search for : 
**test2022** the script will fire **8 requests** to search for the word, while if we have a waiting time until the user finish typing, it will fire only one search request.

Hope I could explain the problem well enough :)

**Comment by sa-si-dev** [comment]
@stefchrif I will add a property to configure the waiting time. Thanks for the suggestion.

**Comment by sa-si-dev** [comment]
@stefchrif this issue has been fixed by @Venkataramanan21 in the [release v1.0.35](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.35)
