### ISSUE TITLE
Do I need to check for the existence of the option I want to select?

### ISSUE THREAD

**Issue by nightrider77** [sa-si-dev/virtual-select#205]
Do I need to check for the existence of the option I want to select if I use onServerSearch mode without predefined options?
Or I can execute addOption method without checking?
Asking because there is no method in plugin for option existence check.

**Comment by sa-si-dev** [comment]
@nightrider77 we need list of options to select value, so that we can display the selected option's label.

To prefill any value, set list of options on initiate.
