### ISSUE TITLE
If I resize my screen below the tipping point of popupDropboxBreakpoint, the dropbox does not change into a popup

### ISSUE THREAD

**Issue by nebulousGirl** [sa-si-dev/virtual-select#206]
I need to use the popup dropbox for screens 1080px and below. The issue here is that some tablets have larger width than 1080px, but when the screen switches to portrait the width will be smaller than 1080px.

I also need the same effect to happen when a window is resized on a large screen. The layout of my page changes a lot below 1080px and the popup is needed to counter some overflow needs for the container of the select elements which makes the inline dropbox disappear.

**Comment by sa-si-dev** [comment]
@nebulousGirl As of now, this plugin doesn't support toggling the dropbox popup on resize.
If needed, you could [destroy](https://sa-si-dev.github.io/virtual-select/#/methods?id=reset) and initiate again on your layout change.

> I also need the same effect to happen when a window is resized on a large screen. The layout of my page changes a lot below 1080px and the popup is needed to counter some overflow needs for the container of the select elements which makes the inline dropbox disappear.

Set `dropboxWrapper: 'body'` property to avoid dropbox disappearing inside the scrollable parent issue.
