### ISSUE TITLE
Is there any way to disable auto scrolling?

### ISSUE THREAD

**Issue by daeyoonlee** [sa-si-dev/virtual-select#208]
Thanks for the great program.

When I open the dropdown again after selecting something, it auto scrolls the selected item to the top. Is there a way to turn off the auto scrolling? The state showSelectedOptionsFirst = false.

**Comment by sa-si-dev** [comment]
@daeyoonlee this is the default behaviour when `showSelectedOptionsFirst` is `false`.

I will add a new property to disable auto scroll in the future release.

**Comment by sa-si-dev** [comment]
@daeyoonlee set `focusSelectedOptionOnOpen: false` property.

This feature is available in the [release v1.0.37](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.37)

**Comment by daeyoonlee** [comment]
It works fine. thank you!
