### ISSUE TITLE
error when markSearchResults: true

### ISSUE THREAD

**Issue by daeyoonlee** [sa-si-dev/virtual-select#209]
Thank you for the great program.

When `markSearchResults: true`, searching with `*` or `(` `)` generates a regular expression error.

![image](https://user-images.githubusercontent.com/68131229/208224500-cf9118ae-0426-4dcd-8b1a-54795d45dd46.png)

![image](https://user-images.githubusercontent.com/68131229/208224423-16e5e179-e877-4962-bde9-6b4494e4abb3.png)

**Comment by sa-si-dev** [comment]
@daeyoonlee thanks for letting me know it. I will check and fix it in the future release.

**Comment by daeyoonlee** [comment]
Thank you

**Comment by gnbm** [comment]
@sa-si-dev I did a [PR](https://github.com/sa-si-dev/virtual-select/pull/212) for this. Please take a look and hope it helps

**Comment by sa-si-dev** [comment]
> @sa-si-dev I did a [PR](https://github.com/sa-si-dev/virtual-select/pull/212) for this. Please take a look and hope it helps 🎄🎅🏻

@gnbm thanks for your contribution. I will merge it in the next release.

**Comment by sa-si-dev** [comment]
@daeyoonlee This issue has been fixed in the [release v1.0.37](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.37)
