### ISSUE TITLE
option unselect not working on multi-level

### ISSUE THREAD

**Issue by Kurousagi94** [sa-si-dev/virtual-select#211]
When I do actions in this order

- Selecting optgroup then all options associated are check and it's checked too : OK
- Scrolling down (until opgroup does not appear animore <- let say 50 options down) : OK
- Unselect one of the options from the checked optgroup <- it's unchecked : OK
- Scrolling up to optgroup label <- it's not checked : ERR

The problem doesn't seem to occur with single level select or when unchecking one of firsts options of optgroup

BTW verry nice plugin :D

**Comment by sa-si-dev** [comment]
@Kurousagi94 if I understood your scenario correctly, it is expected behaviour only.

> Scrolling up to optgroup label <- it's not checked : ERR

If any one of the opt group's child is unchecked, opt group would be unchecked.

**Comment by sa-si-dev** [comment]
@Kurousagi94 this issue has been fixed in the [release v1.0.37](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.37)
