### ISSUE TITLE
Parameter to have dropdown opened by default with a fixed width and height

### ISSUE THREAD

**Issue by jmeierk** [sa-si-dev/virtual-select#22]
Great work. One problem which I still have is that there doesn't seem to be an option to "embed" the dropdown in a fixed space with a defined height and width. For example, it should look similar to the first image under "Preview" here: 

https://www.cssscript.com/select-box-virtual-scroll/

Even though one can use the "position" parameter to define where the dropdown unfolds (top, bottom, auto), I would like to setup a submission form with fixed sizes for most of my components because I don't like that the opened dropdown is overlapping other controls.

Is there an easy workaround for what I described or would you need to implement that first? thx

**Comment by sa-si-dev** [comment]
@jmeierk sorry, I am not getting your requirement.
Could you please give a real time scenario to understand your requirement.

**Comment by jmeierk** [comment]
Sure. When embedding virtual-select in an app, one basically has a dropdown component which has to be clicked to show the available options. The number of display options is defined by noOfDisplayValues.

Now, my question, is there a possibility to avoid clicking the dropdown component to show the available options? That is, can we configure the dropdown in a way that the selectable options are immediately displayed once the form is loaded?

For example have a look at https://sa-si-dev.github.io/virtual-select/#/examples
If you click the dropdown under "default dropdown" a list from "Option 1" to "Option 5" is shown. Can the dropdown component be configured that the dropdown is expanded/opened by default?

**Comment by ahsynv** [comment]
@jmeierk you can use the function "click()" from javascript for this. When page is loaded, you can use it to simulate click on this selectbox to open it by default

Ex : 

`document.querySelector(".vscomp-value").click();`

**Comment by jmeierk** [comment]
Ok, this works! Apart from that is there an option to keep the dropdown permanently opened all the time?

**Comment by sa-si-dev** [comment]
> Sure. When embedding virtual-select in an app, one basically has a dropdown component which has to be clicked to show the available options. The number of display options is defined by noOfDisplayValues.
> 
> Now, my question, is there a possibility to avoid clicking the dropdown component to show the available options? That is, can we configure the dropdown in a way that the selectable options are immediately displayed once the form is loaded?
> 
> For example have a look at https://sa-si-dev.github.io/virtual-select/#/examples
> If you click the dropdown under "default dropdown" a list from "Option 1" to "Option 5" is shown. Can the dropdown component be configured that the dropdown is expanded/opened by default?

@jmeierk I got your requirement. I will work on it in the future release.

BTW it is a good suggestion.

**Comment by sa-si-dev** [comment]
@jmeierk as you requested, I have implemented this feature and it is available in the [release v.1.0.4](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.4)

**Comment by jmeierk** [comment]
thank you so much!!
