### ISSUE TITLE
Switch one option

### ISSUE THREAD

**Issue by AhmedElTabarani** [sa-si-dev/virtual-select#227]
I need to make the user select one option and switch to another if he selected another option 

[Desktop-1676066648296.webm](https://user-images.githubusercontent.com/69223584/218207623-8f8124e9-d53b-464c-87dd-971ed3050046.webm)

**Comment by sa-si-dev** [comment]
@AhmedElTabarani I am not getting your question. Do you wanna allow single select only?

**Comment by AhmedElTabarani** [comment]
> @AhmedElTabarani I am not getting your question. Do you wanna allow single select only?

Yes with this checkbox icon
I know that `multiple: false` will make it single select only but it will make the checkbox disappear.

**Comment by gnbm** [comment]
Using checkboxes on single selections is a tremendous usability mistake in my opinion. Maybe you should challenge that on your project.

**Comment by AhmedElTabarani** [comment]
I convert it to `multiple: false` without checkbox
