### ISSUE TITLE
Method to get labels of selected options

### ISSUE THREAD

**Issue by jmeierk** [sa-si-dev/virtual-select#23]
Is there a method similar to val() for getting the labels of the selected values? Couldn't find it in the docs.
Or is there any quick workaround for achieving this?

**Comment by ahsynv** [comment]
Yes you can get the selected value by "change" event : https://sa-si-dev.github.io/virtual-select/#/events

**Comment by jmeierk** [comment]
This will give me the values but what I need are the shown **labels**. Is there a complementary function to val() which returns the selected labels as array?

**Comment by sa-si-dev** [comment]
> Is there a method similar to val() for getting the labels of the selected values? Couldn't find it in the docs.
> Or is there any quick workaround for achieving this?
> 

@jmeierk I will create a method for this in the future release

**Comment by sa-si-dev** [comment]
@jmeierk as you requested, I have created a method "getDisplayValue()" to get label of selected options.

 This method is available in the [release v.1.0.4](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.4)

**Comment by jmeierk** [comment]
thank you so much!!
