### ISSUE TITLE
Not considering accents when using the search 

### ISSUE THREAD

**Issue by freddidierRTE** [sa-si-dev/virtual-select#238]
Would it be possible, when searching, not considering accents ?

So searching for Pol should return Pôle  

Could be a default behavior or an option ?

**Comment by gnbm** [comment]
@freddidierRTE @sa-si-dev I created a [pull request](https://github.com/sa-si-dev/virtual-select/pull/252) to add this as a new feature. 
Will start has not been applied for backward compatibility

**Comment by gnbm** [comment]
@freddidierRTE A new option called `searchNormalize` was added in the release v1.0.38 that will allow you to achieve this behaviour,

**Comment by freddidierRTE** [comment]
Thanks a lot
