### ISSUE TITLE
showSelectedOptionsFirst doesn't work in Firefox

### ISSUE THREAD

**Issue by mcihak** [sa-si-dev/virtual-select#24]
If I open 
http://plnkr.co/edit/amY5skjS9OL2mr8R?open=lib%2Fscript.js&preview
in Chrome, `showSelectedOptionsFirst` works fine so selected options are displayed at the top of the list. 
If I open the same in Firefox selected options are not moved to the top.

![image](https://user-images.githubusercontent.com/2871726/107763709-57459300-6d2f-11eb-9ce3-5a458626e983.png)

**Comment by sa-si-dev** [comment]
@mcihak good catch, thanks for letting me know this.

**Comment by sa-si-dev** [comment]
@mcihak this issue got fixed and available in the [release v.1.0.4](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.4)
