### ISSUE TITLE
Tooltip not showing: Cannot read property 'insertAdjacentHTML' of null

### ISSUE THREAD

**Issue by geovaneo** [sa-si-dev/virtual-select#25]
Hi,

I followed getting started and documentation, everthing is working fine but tooltip. Whenever I try to see selected options, when I mouse over it:

VM9033:5 Uncaught TypeError: Cannot read property 'insertAdjacentHTML' of null
    at eval (eval at module.exports (VM9004 addScript.js:1), <anonymous>:5:1123)
    at HTMLDocument.l (eval at module.exports (VM9004 addScript.js:1), <anonymous>:5:2395)
eval @ VM9033:5
l @ VM9033:5

Any ideas?

**Comment by sa-si-dev** [comment]
@geovaneo does this error message coming in documents page also or only in your page?

**Comment by mcihak** [comment]
Encountered this issue as well.
The problem was that I placed the script into head of a page.
Try to move tooltip script to the end of the body.

**Comment by geovaneo** [comment]
Hi guys! Moving to end of the body solved the issue. 
Thanks!

**Comment by sa-si-dev** [comment]
@geovaneo this issue got fixed in the tooltip plugin ([v1.0.6](https://github.com/sa-si-dev/tooltip/releases/tag/v1.0.6))

Now we can import plugin files in the `head` tag.
