### ISSUE TITLE
programmatically select a duplicate value when no option selected

### ISSUE THREAD

**Issue by abdullzz** [sa-si-dev/virtual-select#254]
```
    $('#ex-dropdown-input').on('reset', function () {
        document.querySelector('#ex-dropdown-input').setValue("ID")
    });
```
    
  read the docs already, cannot find a way to select an option based on a specific attribute, i have some values that are duplicate, what if i want to use ID attribute for filtering instead of value
  
  meanwhile my options are like this
  ```
{customData: {code: '93', id: 'AF'}, label: "+93 AFG Afghanistan", value: "AF"}
  ```

**Comment by abdullzz** [comment]
tried using this `virtualSelect.selectOption('62');` also didnt work

**Comment by abdullzz** [comment]
for now i switched place, i made the value unique while the code is the value

**Comment by sa-si-dev** [comment]
@abdullzz I don't think it is a best practice to have multiple options with same value.

**Comment by abdullzz** [comment]
@sa-si-dev why not? and in what case? in my case its the best practice. i want both US and Canada to only provide the first number prefix +1 only, cuz some country has more than 1 prefix!
