### ISSUE TITLE
Searching with api

### ISSUE THREAD

**Issue by Sergeant61** [sa-si-dev/virtual-select#26]
Hello, the library you wrote is really nice. However, in the documentation, the search function seems to be valid only for the listed options. I want to use this to request the backend and list the options based on the incoming result. Is there a way to do this? I apologize for my English.

**Comment by ahsynv** [comment]
@sa-si-dev i think you can add a new function named "update()" and possibility access to "options" to make possible to update the data of virtual-select ?

Ex : 

```
var myvirtualselect = VirtualSelect.init({
  ele: '#sample-select',
  options: [
    { label: 'Options 1', value: '1' },
    { label: 'Options 2', value: '2' },
    { label: 'Options 3', value: '3' },
  ],
});
```

and if we need to modify/remove/add any data we can just

```
myvirtualselect.options = [
    { label: 'New options with only 1 value', value: 'test' }
  ];
myvirtualselect.update();
```

**Comment by sa-si-dev** [comment]
@Sergeant61 I will implement it in the future release.

@ahsynv thanks for the suggestion. We alread have [setOptions](https://sa-si-dev.github.io/virtual-select/#/methods?id=setoptions) method to update options list.

But here, whenever search value change, we need to call an API and update options list once get API response, instead of filtring available options list.

**Comment by Sergeant61** [comment]
In addition, when we think of it as input, the "required" property can be brought. These forms will help us.

**Comment by Sergeant61** [comment]
Hello, regarding these issues, I made a fork until @sa-si-dev  made the edits in the main repo. I've added `isShowAllSelectedText`, `searchFromApi`, `required` attributes. After setting `searchFromApi` to `true`, you can listen to `vscomp-search-input` keyup.

**Comment by ahsynv** [comment]
@sa-si-dev thank you for your answer, but i dont understand really the utility to add any "API Support" ( sorry if I say nonsense ). Because finally what @Sergeant61 need ( and other people in the future i imagine ), its to send a data to an API with the current value of search input. And on the side of API we have a response right ? So what we need its just get the current typing value of the search box, and set options to an empty array, send data to API, and if we have any data we can update options, if not we can set options to an empty array ?

I never see an api support on other javascript packages, for example on "chartjs" etc. A javascript package can not do everything for each developer or for each situation, if not, we will have a package very large with a many useless functions. We have "async" functions and "Promises" to work with "API"s and we have a possibility to update the result for "options" in virtual-select, so i dont understand really the need for API support

If you have a clear explanation i would like an answer, it will help me learn more if I am wrong, thanks a lot

**Comment by Sergeant61** [comment]
Actually, my goal is to increase performance. I need the selection box on the website I made. And I don't want to return all the data in the selection box, some of them list length exceeds 30 and the ui is too bad. Therefore, I made a component that is both user-friendly and will be found.

Example [videoUrl](https://drive.google.com/file/d/11BprttLc_8je_OEFWZo6EGS8SAYEWcNV/edit)

**Comment by ahsynv** [comment]
@Sergeant61 the video is private 😕, can you publish it in another way please ? And for the performance issue you can not do anything in the side of the API ? For me, a package need to be "flexible" and "virtual-select" is flexible, we can do many things with the current version, some times we need to do some custom JS to do what we want, and for the API its the same "for me" 😅

**Comment by Sergeant61** [comment]
I made the video public. I think it's open, it's my fault. @ahsynv

**Comment by sa-si-dev** [comment]
@ahsynv you are right. We should not add API related logic in this plugin, but it is good to have a standard way to integrate with API.

I have planned to handle it as below. I will provide a callback function support for search value change event. Project developer has to handle making API call with any method they prefer.

```js
VirtualSelect.init({
  ele: '#sample-select',
  onServerSearch: onSampleSelectServerSearch,
});

function onSampleSelectServerSearch(searchValue, virtualSelect) {
  /** here project developer has to define anyMehodToGetDataFromServer function to make API call */
  anyMehodToGetDataFromServer(searchValue).then(function(newOptions) {
    virtualSelect.setOptions(newOptions);
  });
}
```

**Comment by sa-si-dev** [comment]
> Actually, my goal is to increase performance. I need the selection box on the website I made. And I don't want to return all the data in the selection box, some of them list length exceeds 30 and the ui is too bad. Therefore, I made a component that is both user-friendly and will be found.
> 
> Example [videoUrl](https://drive.google.com/file/d/11BprttLc_8je_OEFWZo6EGS8SAYEWcNV/edit)

@Sergeant61 the main purpose of this plugin is supporting more no.of options without affecting performance.

As you can see in the [docs](https://sa-si-dev.github.io/virtual-select/#/examples) page, It has more than 10 dropdowns and each dropdown has 100,000 options. But you won't feel any performance issue.

P.S. It is not recommanded to use server search, it will affect user experience. But we can do this only in any rare situations.

**Comment by ahsynv** [comment]
> I made the video public. I think it's open, it's my fault. @ahsynv
> There is not much I can do for this on the server side. Listing all the data seems to me a bad way. Correct me if I'm thinking wrong.

If you dont want to get all datas at the one time, i can suggets 2 possibilites ( other people probably have a a better idea than me ) : 

1. When user click on the selectbox, call your API et get/set options for your selectbox

2. Or When user click on the selectbox, call your API get save the data in a JS variable into an array. And when user start to typing you can search the values into your own array and set the options for the virtual select ( i have a suggetion to virtual-select about this at the below )

@sa-si-dev about the 2nd solution, do the "virtual-select" have some property about like "showOptionsOnTyping" ? I looked at the docs but i dont found. Sometimes we can need this feature to dont display all values, and display them only when we start to typing in the "Search" box ? I can simulate an API call and dont show all useless datas ?

**Comment by sa-si-dev** [comment]
> > I made the video public. I think it's open, it's my fault. @ahsynv
> > There is not much I can do for this on the server side. Listing all the data seems to me a bad way. Correct me if I'm thinking wrong.
> 
> If you dont want to get all datas at the one time, i can suggets 2 possibilites ( other people probably have a better idea than me ) :
> 
> 1. When user click on the selectbox, call your API et get/set options for your selectbox
> 2. Or When user click on the selectbox, call your API get and save the data in a JS variable into an array. And when user start to typing you can search the values into your own array and set the options for the virtual select ( i have a suggetion to virtual-select about this at the below )
> 
> @sa-si-dev about the 2nd solution, do the "virtual-select" have some property about like "showOptionsOnlyOnTyping" or "showOptionsOnlyOnSearch" ? I looked at the docs but i dont found. Sometimes we can need this feature to dont display all options, and display them only when we start to typing in the "Search" box ? It can simulate an API call and dont show all useless datas on one time ?

@ahsynv it is a good suggestion. I will implement it with "showOptionsOnlyOnSearch" property.

**Comment by sa-si-dev** [comment]
@Sergeant61 searching with API feature has implemented and available in the [release v1.0.7](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.7) ([more details](https://sa-si-dev.github.io/virtual-select/#/examples?id=server-search))

**Comment by sa-si-dev** [comment]
> > > I made the video public. I think it's open, it's my fault. @ahsynv
> > > There is not much I can do for this on the server side. Listing all the data seems to me a bad way. Correct me if I'm thinking wrong.
> > 
> > 
> > If you dont want to get all datas at the one time, i can suggets 2 possibilites ( other people probably have a better idea than me ) :
> > 
> > 1. When user click on the selectbox, call your API et get/set options for your selectbox
> > 2. Or When user click on the selectbox, call your API get and save the data in a JS variable into an array. And when user start to typing you can search the values into your own array and set the options for the virtual select ( i have a suggetion to virtual-select about this at the below )
> > 
> > @sa-si-dev about the 2nd solution, do the "virtual-select" have some property about like "showOptionsOnlyOnTyping" or "showOptionsOnlyOnSearch" ? I looked at the docs but i dont found. Sometimes we can need this feature to dont display all options, and display them only when we start to typing in the "Search" box ? It can simulate an API call and dont show all useless datas on one time ?
> 
> @ahsynv it is a good suggestion. I will implement it with "showOptionsOnlyOnSearch" property.


@ahsynv I have implemented the feature "showOptionsOnlyOnSearch".

It is available in the [release v1.0.8](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.8) ([more details](https://sa-si-dev.github.io/virtual-select/#/examples?id=show-options-only-on-search))

**Comment by yahyaerturan** [comment]
Well, it is not directly about the question but the title of the question may help others, that's why I am writing to here.

`onServerSearch` works like a charm in create forms. My question for edit forms. How can we display the option selected on a ServerSearch vscomp?

**Comment by sa-si-dev** [comment]
@yahyaerturan, we could implement it by setting options property with selected value's options on initialization

```js
VirtualSelect.init({
  ele: '#sample-select',
  onServerSearch: onSampleServerSearch,
  selectedValue: 2,
  options: [
    { label: 'Options 2', value: '2' },
  ],
});
```
