### ISSUE TITLE
Is it able to select the selectAll option by any key of keyboard?

### ISSUE THREAD

**Issue by dawzl** [sa-si-dev/virtual-select#268]
Is it able to select the selectAll option by any key of keyboard?

**Comment by sa-si-dev** [comment]
> Is it able to select the selectAll option by any key of keyboard?

@dawzl as of now, it is not possible.

**Comment by gnbm** [comment]
@dawzl In terms of accessibility best practices, the common keyboard key used to select all options in a dropdown (select element) is the "Ctrl" key (or "Command" key on macOS) in combination with the mouse click. When a user clicks an option with the "Ctrl" (or "Command") key held down, it typically toggles the selection state of that option while keeping other selections intact.
With this in mind, I ran some tests and his combination works 🤔
