### ISSUE TITLE
"search" proprerty set true the "disableSelectAll"

### ISSUE THREAD

**Issue by ahsynv** [sa-si-dev/virtual-select#27]
Hi, when we set "search" proprerty to "false" the "Select all" button disappears, i try to set "disableSelectAll" => "false" manually but its not working. Can we just get the "Select all" button without "Search" ?

**Comment by sa-si-dev** [comment]
@ahsynv this issue got fixed and available in the [release v1.0.6](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.6)

**Comment by sathio** [comment]
I think this regressed, I need the search button to make http requests and fill the array of options, but I don't see the "select all" option.
