### ISSUE TITLE
Display tooltip on truncated labels in tags (multiple mode)

### ISSUE THREAD

**Issue by abenhamdine** [sa-si-dev/virtual-select#270]
First, thx for this wonderful component ! ❤️ 
We are currently migrating our codebase to use virtual-select everywhere and it works fine 👍 

Currently, it looks like a tooltip is displayed only when the single selected value overflows in the select, but there's no tooltip on tags when the `multiple` mode is enabled : 
See for instance below, the text is truncated but there's no tooltip
<img width="411" alt="image" src="https://github.com/sa-si-dev/virtual-select/assets/7466144/f6d05a7c-1ff4-4433-9d4b-82e23e38dde1">

would it be possible to add this feature ?

**Comment by gnbm** [comment]
@abenhamdine could you please share the scenario (code pen or similar) where you're not getting the tooltip?

**Comment by gnbm** [comment]
@abenhamdine I created a [PR](https://github.com/sa-si-dev/virtual-select/pull/286) to add this behaviour for tags.
cc: @sa-si-dev

**Comment by gnbm** [comment]
Fixed in release [v1.0.41](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.41)
