### ISSUE TITLE
Issue on Dropdowns autofocusing when setting starting options

### ISSUE THREAD

**Issue by gnbm** [sa-si-dev/virtual-select#271]
- Issue on Dropdowns autofocusing when setting starting options:

![IssueAutoFocusVS](https://github.com/sa-si-dev/virtual-select/assets/29493222/47b365cf-c2e9-48b7-93eb-7fdfa4671755)

- Was introduced in PR - [Guarantee that the select is focus after the component is closed; by JoaoFerreira-FrontEnd · Pull Request #256 · sa-si-dev/virtual-select](https://github.com/sa-si-dev/virtual-select/pull/256/files)

**Comment by gnbm** [comment]
@sa-si-dev Created [this PR](https://github.com/sa-si-dev/virtual-select/pull/272) to roll back the unwanted behaviour that was introduced.

**Important Note:**
The original issue that the [PR](https://github.com/sa-si-dev/virtual-select/pull/256/files) wanted to address will still occur so it will need to be done differently and here maybe you could quickly fix this differently since you know much better all the component lifecycle and events.

**Comment by sa-si-dev** [comment]
@gnbm no need to rollback the privious change.
I have checked-in the fix for this issue. But it hasn't released yet.
[https://github.com/sa-si-dev/virtual-select/commit/fd407b828c2513095aba5ab4739e44ed7c9a2c63](https://github.com/sa-si-dev/virtual-select/commit/fd407b828c2513095aba5ab4739e44ed7c9a2c63)

**Comment by gnbm** [comment]
@sa-si-dev Will run some tests and will give you some feedback. Meanwhile, closed the PR. Cheers

**Comment by gnbm** [comment]
@sa-si-dev Just a follow-up. Just run a batch of tests with the change you did in the [commit](https://github.com/sa-si-dev/virtual-select/commit/fd407b828c2513095aba5ab4739e44ed7c9a2c63) and it works perfectly.
Do you have a release planned? 
Thank you!

**Comment by sa-si-dev** [comment]
> @sa-si-dev Just a follow-up. Just run a batch of tests with the change you did in the [commit](https://github.com/sa-si-dev/virtual-select/commit/fd407b828c2513095aba5ab4739e44ed7c9a2c63) and it works perfectly.
> Do you have a release planned? 
> Thank you!

Could you please create a new release with this issue fix only.

**Comment by sa-si-dev** [comment]
@gnbm  This issue has been fixed in the release [v1.0.40](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.40)

**Comment by sa-si-dev** [comment]
> > Could you please create a new release with this issue fix only
> 
> @sa-si-dev Sure, I'll try to do it this week and ask for your validation since I still can't run the tests or the validate command without getting tons of errors.
> Would it be possible to also have your help on fixing these issues: #162 / #169 / #244? They are having some impact and I don't know the library enough yet to be able to quickly fix them. It would be really helpful!
> 

@gnbm I will fix other issues in the future release.

**Comment by gnbm** [comment]
> > > Could you please create a new release with this issue fix only
> > 
> > 
> > @sa-si-dev Sure, I'll try to do it this week and ask for your validation since I still can't run the tests or the validate command without getting tons of errors.
> > Would it be possible to also have your help on fixing these issues: #162 / #169 / #244? They are having some impact and I don't know the library enough yet to be able to quickly fix them. It would be really helpful!
> 
> @gnbm I will fix other issues in the future release.

@sa-si-dev That would be amazing since the impacts on my case are quite big. Cheers
