### ISSUE TITLE
Using a custom scrollbar such as overlayscrollbar

### ISSUE THREAD

**Issue by Dams591** [sa-si-dev/virtual-select#28]
Hey,

Just trying out virtual-select and got to say this is an incredible piece of work ! awesome project @sa-si-dev  ! 
Wanted to ask you if you had any idea on how to integrate a custom scrollbar such as Overlayscrollbar (https://github.com/KingSora/OverlayScrollbars) to replace the browser scrollbar.

Been trying to instanciate the pluging on elements with the class 'vscomp-options-container' but as you can see here on this codepen https://codepen.io/dams591/pen/zYojWNb I'm losing the virtualization of items while scrolling :( 

Thanks,
Damien

**Comment by sa-si-dev** [comment]
@Dams591 it seems this plugin adds some extra DOM elements inside `.vscomp-options-container`, which affect the logic I have used for virtual scroll.

It is not recommanded to use scroll plugin with virtual select. I think you can customize the scrollbar in CSS itself.

https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp

With plugin

<img width="827" alt="Screenshot 2021-03-02 at 9 01 42 PM" src="https://user-images.githubusercontent.com/76465932/109672318-ea3d5480-7b9a-11eb-8f2a-75074eb6b57f.png">

Without plugin

<img width="827" alt="Screenshot 2021-03-02 at 9 02 13 PM" src="https://user-images.githubusercontent.com/76465932/109672335-ef020880-7b9a-11eb-9c5f-40e67ee642eb.png">

**Comment by Dams591** [comment]
@sa-si-dev css yeah I was trying to maintain the same style accross all browsers by using a js plugin ( firefox only allow for certain customisations, IE 11 doesn't support css at all and so on...) but I guess I can live with it. Thanks anyway.
