### ISSUE TITLE
Possibly display tooltip in case all options are selected

### ISSUE THREAD

**Issue by mcihak** [sa-si-dev/virtual-select#29]
Tooltip is not displayed when all options are selected. I can see in the code that the case when all options are selected is handled separately and `data-tooltip` attribute is not set in this case. It might be intentional.  

In case of our application this is not ideal because we dynamically change the list of options and preselect them all by default. From user experience point of view it might seem like an inconsistent behavior:
- all options are selected, tooltip is not available
- all but one option is selected, tooltip is available

What is your opinion? Do you think it makes sense to display a tooltip with list of options even in case when all options are selected? Considering our use case this would be welcomed.

**Comment by sa-si-dev** [comment]
@mcihak I will add a property to show tooltilp on selecting all options in the future release.

**Comment by sa-si-dev** [comment]
@mcihak this feature has implemented as [hideValueTooltipOnSelectAll](https://sa-si-dev.github.io/virtual-select/#/properties) and available in the [release v1.0.7](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.7)

**Comment by mcihak** [comment]
@sa-si-dev great thanks for implementing the feature 👍
