### ISSUE TITLE
Disabled elements are still functional if accessed via the keyboard

### ISSUE THREAD

**Issue by rid9** [sa-si-dev/virtual-select#290]
To reproduce:

1. Visit the [Disable/Enable](https://sa-si-dev.github.io/virtual-select/#/examples?id=disableenable) example from the documentation.
2. Uncheck the "Enable" checkbox. The select now looks disabled as expected, and it's not possible to control it with the mouse.
3. Click on the select from the example above to focus it.
4. Press Tab a few times until the disabled checkbox receives focus.
5. You can now use the keyboard to control the disabled checkbox. Enter works and it opens the dropdown, then you can navigate with the arrow keys to select an option.

When a select is disabled, it should ignore focus and it should not be possible to navigate to it or to control it with the keyboard.

As an example, if three select elements are next to each other and the one in the middle is disabled, pressing Tab should move focus from the first select to the last select and ignore the select in the middle.

**Comment by gnbm** [comment]
@rid9 this should be already fixed in [this PR](https://github.com/sa-si-dev/virtual-select/pull/276) that is pending a review for quite a while

**Comment by rid9** [comment]
@gnbm, [v1.0.41](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.41) fixed this as well.

**Comment by gnbm** [comment]
Fixed in release [v1.0.41](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.41)
