### ISSUE TITLE
Dropdown doesn't close when using Tab to unfocus a select.

### ISSUE THREAD

**Issue by rid9** [sa-si-dev/virtual-select#291]
To reproduce:

1. Visit the [examples page](https://sa-si-dev.github.io/virtual-select/#/examples) in the documentation.
2. Click on the first select to open its dropdown.
3. Press Tab.

This will focus the next element on the page without closing the dropdown. If you press Tab a few more times, you will be able to focus the next select, and pressing Enter will open that select's dropdown. Now you'll have two dropdowns visible on the page at the same time.

The dropdown should be closed whenever the select loses focus, whether that happens as a result of a mouse event or a keyboard event. Right now, this only happens for mouse events.

**Comment by abenhamdine** [comment]
Actually I can reproduce this behaviour only for the first select in the demo, without searchbox.
If you unfocus with Tab in the following examples, with searchbox, it works

**Comment by rid9** [comment]
> Actually I can reproduce this behaviour only for the first select in the demo, without searchbox. If you unfocus with Tab in the following examples, with searchbox, it works

Indeed, if you open a select with search, pressing Tab will close the dropdown as expected. This only happens if the search bar is enabled though.

For example, if you go to the [Multiple select without search](https://sa-si-dev.github.io/virtual-select/#/examples?id=multiple-select-without-search) example, you can Tab to the next two examples and open a total of three dropdowns at the same time. Also, if you press Tab on the select with search and arrive at the next select, which doesn't have search enabled, you can still open it, and now you have four dropdowns open at the same time.

**Comment by gnbm** [comment]
[@joserio](https://github.com/joselrio) Does your [PR](https://github.com/sa-si-dev/virtual-select/pull/276) fixes this as well?

**Comment by gnbm** [comment]
@rid9 / @abenhamdine could you please check if this was properly fixed in release [v1.0.41](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.41) so we can close this?

**Comment by gnbm** [comment]
Fixed in release [v1.0.41](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.41)

**Comment by rid9** [comment]
@gnbm, v1.0.41 did fix the issue, thank you, but it's a bit inconsistent.

The dropdown does close when you use Tab, but only if you have a search box or multiple select. If you have none of these, then it doesn't close, but the focus is trapped inside the dropdown, so that works as well.
