### ISSUE TITLE
Optgroup feature ?

### ISSUE THREAD

**Issue by ahsynv** [sa-si-dev/virtual-select#3]
Hi, I would like to thank you for this great job, this is really good !
Is it possible to add the new feature like optgroup ?
Thanks a lot in advance

**Comment by sa-si-dev** [comment]
Thank you for your feedback.

I will implement it in the future release.

**Comment by sa-si-dev** [comment]
> Hi, I would like to thank you for this great job, this is really good !
> Is it possible to add the new feature like optgroup ?
> Thanks a lot in advance

@ahsynv  as you requested, I have implemented the feature to allow optgroup.

This feature is available in the [release v.1.0.3](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.3) ([more details](https://sa-si-dev.github.io/virtual-select/#/examples?id=option-group))

**Comment by ahsynv** [comment]
You are the BEST ! thank you very much i love this feature 😍
