### ISSUE TITLE
Scrolling issue.

### ISSUE THREAD

**Issue by Dams591** [sa-si-dev/virtual-select#30]
Hello @sa-si-dev,

Still playing around with your work and now facing various scrolling issues.
I'm not sure why but the number of items seems related (not facing the issue with 100 items but with 10 I am)

Here's a few scenarios:

Using https://codepen.io/dams591/full/zYojWNb (10 items per dropdown)

Scenario A.

1. Go hover the second dropdown (list with search) and use mouse wheel to scroll to the end => Notice that the dropdown scroll to the end
2. Attempt to scroll back to the top using the mouse click on scroll bar => Notice that the scroll bar is not moving back up 

Scenario B
1. Go hover the second dropdown (list with search) and use mouse wheel to scroll to the end => Notice that the dropdown scroll to the end
2. Attempt to scroll back to the top and then back to the bottom => the scroll bar will stay stuck at one point
If 2. doesn't happen keep using mousewheel down and then up it will stay stuck at one point.

I first thought it was because of codepen and my forked version of your code but I'm facing a similar issue here:
https://sa-si-dev.github.io/virtual-select/#/examples 
around the "option group" section.

I'm using MS edge (chromium) Version 88.0.705.81 but I'm able to get a stuck scroll bar on your example page (option group again) on firefox 86.0
I'm on windows, but scrolling issues seems worse on macos and/or ios.

Here's a gif showing Scenario A.
Thanks.
![scroll](https://user-images.githubusercontent.com/12731716/109821620-73559980-7c36-11eb-950c-ba1d57a1e264.gif)

**Comment by sa-si-dev** [comment]
@Dams591 I will check and fix them.

Thanks for letting me know.

**Comment by Dams591** [comment]
@sa-si-dev 
Not sure why and also what that breaks but if I remove the call to this.moveFocusedOptionToView(); in renderOptions() (last line of the function) I get a clean and smooth scrollbar ;)

**Comment by sa-si-dev** [comment]
> @sa-si-dev
> Not sure why and also what that breaks but if I remove the call to this.moveFocusedOptionToView(); in renderOptions() (last line of the function) I get a clean and smooth scrollbar ;)

@Dams591 I think this is the cause of the issue. Thanks for finding it out.

I don't remember why I added that line. Will remove it if that line is not needed.

**Comment by sa-si-dev** [comment]
@Dams591 this issue got fixed and available in the [release v1.0.7](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.7)
