### ISSUE TITLE
when using server search, disableSelectAll doesn't work

### ISSUE THREAD

**Issue by sathia-musso** [sa-si-dev/virtual-select#300]
As per the title, it seems impossible to search and select all options with one click. 
i'm using the latest version.

and also, it seems that `document.querySelector('#virtual-select2NPFFOAX00').toggleSelectAll(true);` doesn't work either

**Comment by gnbm** [comment]
@sathio could you please share a codepen(or similar) with those use cases?

**Comment by sathio** [comment]
> @sathio could you please share a codepen(or similar) with those use cases?

https://codepen.io/Sathio/pen/QWogJMv

**Comment by gnbm** [comment]
Looking into the code this doesn't seem like an issue but something that is working as expected as per this logic:
![image](https://github.com/sa-si-dev/virtual-select/assets/29493222/3a0ee7d7-3f69-423b-bdcf-6d2cbd70f76f)

**Comment by sathio** [comment]
well, it looks like it's not a very clever logic doesn't it?

i mean, why shouldn't I be able to select options I'm actually searching for?
I think I'll just monkey patch locally and see how it works for me. thanks anyway!

**Comment by gnbm** [comment]
No idea about the reason. Probably @sa-si-dev is the person who can answer that.

**Comment by sathio** [comment]
I can confirm that by monkey patching it it _seems_ to be working fine
