### ISSUE TITLE
The "disabled" property doesn't account for the tabindex.

### ISSUE THREAD

**Issue by alexandre97costa** [sa-si-dev/virtual-select#305]
The boolean property can be set, but it seems like it only changes the appearance of the component. The issue here is that even when it is disabled, it is focusable via keyboard (and it shoulnd't). I don't think this is the expected behaviour, as there are no additional styles for this specific use-case. The fix would be to set the tabindex to -1, as is documented [in the MDN Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) as best practice when an element is temporarily inacessible.

To recreate this use-case, you can create two components: the first with the "disabled" property set to false, the second set to true. Then in the console, [detect the focused element](https://devtoolstips.org/tips/en/track-focused-element/). Click on the first dropdown to focus it, and press tab to focus on the next dropdown. In the console you can check it it focused, when it shouldn't.

**Comment by joselrio** [comment]
Hi @alexandre97costa,
Are you using the lts version available?
Asking it once at examples page https://sa-si-dev.github.io/virtual-select/#/examples?id=disableenable, by updating disabled attribute, a disabled attribute is being added to the input, which makes input not achievable on tabs navigation. 
Also by default, if an input gets disabled attribute it does not need tabindex=-1, since browser and assistive technologies are aware about it since it's a native attribute as well.
Cheers,
JR

**Comment by alexandre97costa** [comment]
My version has an invisible input which gets disabled like you say, yes. But this version also has a wrapper with a tabindex attribute, which does not change with the disabled option.
I tried to search for something wrong in the source, but there is logic implemented to change this value. I do not understand why it is not working. I'm using this component inside OutSystems UI, which might be the culprit of the bug.

**Comment by alexandre97costa** [comment]
Hi @joselrio, I noticed you also work with OutSystems. I am using the DropdownSearch widget, and below are my attempts at solving this:

- Changing the IsDisabled field under OptionalConfigs. I set it to a boolean variable, which changes the appearance of the widget but doesnt change the tabindex.
- Calling the Client Action "DropdownDisable" that comes with OutSystems UI. It ran on the Initialize event of the Dropdown, outputed a Success response and gave me the same thing: Disabled appearance, unchanged tabindex.
- Using Javascript. The Dropdown Widget Id given by OutSystems gives me a parent element to the one which includes all the custom functions (as is proven by the browser dev tools). I called the element.firstChild.disable() similar to the example you gave. Same result: disabled appearance, disabled attributes were inserted, but no change in the tabindex.

Im going to use SetAttribute to temporarily solve my issue. If you have any updates on this issue please let me know. If needed, I can provide more tests for repro.

**Comment by gnbm** [comment]
@alexandre97costa I think this is not the right forum to address those topics related to specific technologies besides focusing on the library as an opensource project available for all to contribute.

**Comment by joselrio** [comment]
Hi @alexandre97costa, well, you can raise a community forum post or a support case for this, under the right scope, it's the best way to get the help you need.

**Comment by alexandre97costa** [comment]
Hello @joselrio @gnbm, I checked this issue further and noticed the version of virtual select I'm using is v1.0.37, while the latest (released today 🥳) is 1.0.41. This latest version added new accessibility features, so I will close this issue for the time being and open a new one if the problem persists in the new version. Thank you for your time, and happy weekend!

Cheers,
Alexandre Costa
