### ISSUE TITLE
Inline Style Css Properties is not Showing

### ISSUE THREAD

**Issue by shabranali786** [sa-si-dev/virtual-select#306]
![Screenshot 2024-01-27 213503](https://github.com/sa-si-dev/virtual-select/assets/106592342/d25fa37d-eb92-4e20-b396-534036b5a9f4)
![image](https://github.com/sa-si-dev/virtual-select/assets/106592342/2ea8b89d-2140-4165-b915-77628ec6f820)

**Comment by gnbm** [comment]
@shabranali786 could you share a CodePen with your implementation and explain your use case? 
Despite not being a good practice to use inline styles, are you sure you're applying that to the right element and at the right time on the component's lifecycle?
