### ISSUE TITLE
Add property in the documentation

### ISSUE THREAD

**Issue by Widdou** [sa-si-dev/virtual-select#309]
The 'setOptions()' method is missing one property in its documentation.
The 'noEventTrigger' listed in the 'setValue()' method is also available for this method.

It's good to know when you need to initially populate the dropdown without triggering validations

**Comment by gnbm** [comment]
@Widdou For the `setOptions` method is there a missing parameter or a parameter (`keepValue`) that shouldn't even be there?
Looking into the code I can only see the parameter `options = []` and there's another method called `setOptionsMethod` that contains also `keepValue` but never the one you're mentioning. Maybe I'm missing something but feel free to open a PR so @sa-si-dev can validate
