### ISSUE TITLE
Add classes to button

### ISSUE THREAD

**Issue by hawkeye116477** [sa-si-dev/virtual-select#312]
It's possible to add classes to wrapper and options, but not to `.vscomp-toggle-button` . So it would be good if will be something named `additionalButtonClasses`, so it will be possible to use Bootstrap or another framework classes.

**Comment by gnbm** [comment]
> It's possible to add classes to wrapper and options, but not to `.vscomp-toggle-button` . So it would be good if will be something named `additionalButtonClasses`, so it will be possible to use Bootstrap or another framework classes.

@hawkeye116477 can you give an example where you can show the element that would have those classes and explain the use cases (with practical examples) where that could be used?

**Comment by raliqala** [comment]
Let's say I wanted to add tailwind classes to customize the select input, is this possible or I can add classes for specific elements.

**Comment by gnbm** [comment]
@raliqala I think the same would be useful for the element with the class `vscomp-dropdox` to allow styling the dropdown balloon.
