### ISSUE TITLE
The search input is disabled when allowNewOption is set to true and the options are empty.

### ISSUE THREAD

**Issue by funnygod** [sa-si-dev/virtual-select#313]
When I try to use allowNewOption with an empty option, it also causes the search input to be disabled. Could you please enable the search input when allowNewOption is true? it worked perfectly before version 1.0.41
![image](https://github.com/sa-si-dev/virtual-select/assets/2239417/bf21086b-3da4-4cdc-8893-36efb2bc08a6)

**Comment by gnbm** [comment]
@funnygod Can include a working example for your scenario?.
I might also be missing something but I'm not being able to replicate what you mentioned, so an example with your configs and steps to reproduce would be great, as well as clarify what you mean by `empty option`?

**Comment by gnbm** [comment]
> > @funnygod Can include a working example for your scenario?. I might also be missing something but I'm not being able to replicate what you mentioned, so an example with your configs and steps to reproduce would be great, as well as clarify what you mean by `empty option`?
> 
> Hi @gnbm Here is the example of 1.0.40 that working https://codepen.io/lim-chong-hooi/pen/vYMNyRN
> 
> Here is a example of version 1.0.41 where the search input has been disabled. https://codepen.io/lim-chong-hooi/pen/OJGybam

@funnygod In a couple of days I'll  try to create a PR with a fix for this since I was already able to figure out what's the problem

**Comment by funnygod** [comment]
> @funnygod Opened a [PR](https://github.com/sa-si-dev/virtual-select/pull/315) that includes a fix for this. Can you please review it while I wait for @sa-si-dev validation?

@gnbm  I've tested it, and it's working well
