### ISSUE TITLE
Search Feature Unresponsive After Setting an Empty List of Options

### ISSUE THREAD

**Issue by freddidierRTE** [sa-si-dev/virtual-select#318]
Starting from version 1.0.41, a problem arises with the search feature in the virtual select functionality. If the list of options is emptied and then repopulated, the search feature ceases to function correctly.

This repository provides all necessary information and code to reproduce the issue: [https://github.com/opfab/virtual-select-issue](https://github.com/opfab/virtual-select-issue)

**Comment by abenhamdine** [comment]
probably the same issue I ran into : https://github.com/sa-si-dev/virtual-select/issues/297

**Comment by gnbm** [comment]
> Starting from version 1.0.41, a problem arises with the search feature in the virtual select functionality. If the list of options is emptied and then repopulated, the search feature ceases to function correctly.
> 
> This repository provides all necessary information and code to reproduce the issue: https://github.com/opfab/virtual-select-issue

@freddidierRTE To try to fix this I created the following PR https://github.com/sa-si-dev/virtual-select/pull/321
Great work on providing a sample to reproduce the issue on that repo 💪🏻
Could you please review it? 
@sa-si-dev Could you please validate it as well?

**Comment by gnbm** [comment]
Fixed in release [v1.0.43](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.43).
