### ISSUE TITLE
Crop selector and no popup on mobile screen

### ISSUE THREAD

**Issue by PCov3r** [sa-si-dev/virtual-select#33]
Hello,
I have a small problem with selector. On a full webpage it works like a charm. The selector shows 5 items, no problem.

But if I reduce width, like on mobile phone or when resizing the window, the selector doesn't show these 5 items. In fact if it is full screen, the items are shown below the selector box, whereas if it is in a reduced window, there are shown above the selector window (see attached pictures) and that may be why things get cropped.
Moreover, I don't get the popup select box if I'm on a mobile phone...

![No crop](https://user-images.githubusercontent.com/38764918/114286630-d0781280-9a60-11eb-943f-dd4c7174eea1.PNG)
![crop](https://user-images.githubusercontent.com/38764918/114286657-0ae1af80-9a61-11eb-8544-ca2d7be91e2e.PNG)

I don't quite see where the problem could come from...

If you have any clue, please let me know.

Great plugin by the way !
Regards

**Comment by sa-si-dev** [comment]
It seems ancestor element of dropdown has `overflow: hidden` property.

By default dropbox would be shown on top or bottom based on which part has more space.

You can try any of the below solutions.

- Remove `overflow: hidden` property from ancestor element
- Always show dropbox below by setting `position: 'bottom'` property while initialization or by inline attribute `data-position="bottom"`

<br>

> I don't get the popup select box if I'm on a mobile phone...

If your mobile has more than `576px` try after setting more pixel by `popupDropboxBreakpoint: '700px'`.

If it is not working share the code you are using to initialize the virtual select

**Comment by PCov3r** [comment]
It was indeed an `overflow: hidden` problem !
Thanks ! 

I also figured the problem with the popup. It is because I forgot the meta tag in the `<head>`
Everything is now perfectly working.
