### ISSUE TITLE
How can we fire the first api call to onServerSearch on init

### ISSUE THREAD

**Issue by yahyaerturan** [sa-si-dev/virtual-select#35]
Thanks again @sa-si-dev . Now this is the main component we use for every select/dropdown in our apps.

I have on question: I have implemented a vscomp with `onServerSearch` property. It is working great. To provide a better user experience, I want to fire the first search call with and empty query string (meaning get all by pagination applied in my system) and load those options first from api. It might be better than opening an empty options box (user can now better what kind of text they should be search for). How can I achieve that?

```javascript
VirtualSelect.init({
    ...
    onServerSearch: function (searchValue, virtualSelect) {
        var searchUrl;
        searchUrl = $("#productTypeDropdown").data("search-api");
        $.ajax({
            url: searchUrl+"?term="+searchValue,
            method: "GET",
        }).done(function (data) {
            virtualSelect.setServerOptions(data);
        });
    },
    ...
```

First api call to be fired empty naturally as:

`searchUrl?term=''` 

I thought it can be done with events but on documentation I see only change event. 

Thanks for help!

**Comment by sa-si-dev** [comment]
@yahyaerturan, you could implement it by calling the `onServerSearch` callback function after initializing VirtualSelect.

```js
var sampleVirtualSelect = VirtualSelect.init({
  ...
  onServerSearch: onSampleServerSearch,
});

onSampleServerSearch('', sampleVirtualSelect);
```
