### ISSUE TITLE
Autofocus even when autofocus is set to false

### ISSUE THREAD

**Issue by slinkymanbyday** [sa-si-dev/virtual-select#354]
When creating a dropdown with the below code:
`VirtualSelect.init({ ele: this, search: true, zIndex: 1000, maxWidth: maxWidth, autofocus: false });`

The page autofocuses to the dropdown element.

This issue appears to only happen in 1.0.45
I have tested versions going back to 1.0.40, and prior versions seems to be ok.
My guess is it has to do with this line: https://github.com/sa-si-dev/virtual-select/pull/350/files#diff-7075f90f187d4b281f22b3136982040883bc7595e92f73267c6e47868729dd64R2359 

commenting it out on version 1.0.45 seems to solve the issue, however I'm not proficient in JS enough to dig deeper than that.

**Comment by gnbm** [comment]
@slinkymanbyday I was also able to reproduce a similar issue but only when the dropdown has initial values.
Could you share a sample in codepen or similar with your particular use case?

**Comment by slinkymanbyday** [comment]
it happens when I'm setting initial values, I just noticed the silentInitialValueSet param. I'll try that and see if it helps

**Comment by slinkymanbyday** [comment]
Can confirm that silentInitialValueSet has worked for me. still kinda strange that focus happens when this value is true, but since it's working happy for this issue to be closed.
