### ISSUE TITLE
Textbox not updating when an option is unselected.

### ISSUE THREAD

**Issue by moussa1** [sa-si-dev/virtual-select#37]
If I select 3 options and close, the label shows "3 options selected", however when I unselect an option, the label still shows "3 options selected".

**Comment by sa-si-dev** [comment]
@moussa1 please share the code you are using to initialize dropdown.

**Comment by moussa1** [comment]
<script type="text/javascript">

			var types;
			var Main = [];
			var virtualSelectVar;

			$(document).ready(function() {
				var element = parent.$("iframe[data-id='WebResource_Component4afdfbe-33cfa26a-64d4-43f1-b426-38a0e0a844f8_WebResource_Component4afdfbe']");
				element[0].style.border = "0";
				
				$(document).on('click', '#box3', function() { GetRegionDetails();});
		
				function GetRegionDetails() {
					parent.Xrm.WebApi.retrieveMultipleRecords("mcs_region", "?$select=mcs_name,mcs_inpanicmode,mcs_regionid").then(
						function success(result) {
							if (result.entities.length > 0) {
								$( "#panicdetails" ).show( "fade" );
								$( ".quotes" ).hide( "fade" );

								$('#panicdetails').parent().css("justify-content", "left"); 
								$('#panicdetails').parent().css("align-items", "inherit"); 
								
								$('#panicdetails').parent().parent().css("border", "0px"); 
								
								console.log("SECOND " + types);
									
								for (var i = 0; i < result.entities.length; i++) {
														
									var regionid = result.entities[i].mcs_regionid;
									var inpanicmode = result.entities[i].mcs_inpanicmode;
									var name = result.entities[i].mcs_name;
									
									var stringBuilder = "<div class='panicContainer'><h3 class='labelH3'>" + name + "</h3>";
									
									//add disaster types dropdownlist
									if (types.length > 0)
									{
										stringBuilder += '<div class="panicSelectContainer" id="select_' + regionid + '"></div>';
									}
									
									for (var j = 0; j < types.length; j++) {
																	
										var option = {};
										option.label = types[j].mcs_name;
										option.value = types[j].mcs_disastertypesid;
										Main.push(option);
									}
									
									stringBuilder += "<div class='panicSwitchContainer'><div class='switch' id='switch'>"+'<input class="cmn-toggle cmn-toggle-round" type="checkbox" id="togBtn_' + regionid + '" data-value="' + i + '" />';
									stringBuilder += '<label for="togBtn_' + regionid + '"></label></div>';

									$('#panicdetails').append(stringBuilder);
									
									$("#togBtn_" + regionid).prop("checked", inpanicmode);
									
									var select_selector = '#select_' + regionid;
									
									virtualSelectVar = VirtualSelect.init({
									  ele: select_selector,
									  options: Main,
									  search: true,
									  multiple: true
									});	
									
									
									var chkbox = "#togBtn_" + regionid;
									
									$(chkbox).change(function() {
										if(this.checked) {
											var returnVal = confirm("Are you sure you want to turn panic mode ON?");
											$(this).prop("checked", returnVal);
											
											if (returnVal)
											{
												$("#select_" + ($(this).attr('id')).substr(($(this).attr('id')).lastIndexOf("_")+1)).show();
												
											}
										}
										else{
											$("#select_" + ($(this).attr('id')).substr(($(this).attr('id')).lastIndexOf("_")+1)).hide();
										}
									});
									
									if (!inpanicmode)
									{
										$(select_selector).hide();
									}
								}
							}
						},
						function (error) {
							console.log(error.message);
						}
					);
				}

				function GetDisasterTypes() {
						parent.Xrm.WebApi.retrieveMultipleRecords("mcs_disastertype", "?$select=mcs_name,mcs_disastertypeid").then(
							function success(typesresult) {
								types = typesresult.entities;
								console.log("FIRST " + typesresult);
							},
							function (error) {
								console.log(error.message);
								// handle error conditions
							}
						);
				}
			
			GetDisasterTypes();
			
			});

		</script>

**Comment by sa-si-dev** [comment]
@moussa1 please check that does multiple dropdown options has same value.

**Comment by moussa1** [comment]
Yes multiple dropdown options will have same value... how can i fix this issue pls?

**Comment by moussa1** [comment]
never mind i got it working. thank you
