### ISSUE TITLE
Put forward selected elements when showing

### ISSUE THREAD

**Issue by ahsynv** [sa-si-dev/virtual-select#4]
Is it possible to add new feature with a new propertie for example named "forwardSelected", and when its true, all selected elements will be show first. Because when we have 50+ elements, we need to scroll down to see which options are checked or not

Thanks !

**Comment by sa-si-dev** [comment]
Sure. It is a good feature to have. I will implement it in the future release.

**Comment by sa-si-dev** [comment]
> Is it possible to add new feature with a new propertie for example named "forwardSelected", and when its true, all selected elements will be show first. Because when we have 50+ elements, we need to scroll down to see which options are checked or not
> 
> Thanks !

@ahsynv  as you requested, I have implemented the feature to showing selected options first.

This feature is available in the [release v.1.0.3](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.3) ([more details](https://sa-si-dev.github.io/virtual-select/#/examples?id=showing-selected-options-first))

**Comment by ahsynv** [comment]
Amazin you are very fast thanks a lot !!! 🎉👌👏
