### ISSUE TITLE
Memory leak after recent implementation of labelRenderer

### ISSUE THREAD

**Issue by Goatform** [sa-si-dev/virtual-select#42]
**Issue explanation:** - read issue title -

**How to reproduce the issue?**
Populate dropdown with 10+ rows and then **click on the select input and scroll through the options**.
Then **you will start seeing `labelRenderer` getting triggered so many times**, the more you scroll the worse it gets to the point where the **browser stops interacting**.

**Example code** is exactly the same as the one from documentation, I only added `console.log` for it to see what I'm talking about.
``` javascript
function sampleLabelRenderer(data) {
  let prefix = '';
  console.log("Triggered");
  /** skipping options those are added newly by allowNewOption feature */
  if (!data.isCurrentNew && !data.isNew) {
    /** project developer has to add their own logic to create image/icon tag */
    let flagIndex = data.value % flagClasses.length;
    prefix = `<i class="flag flag-${flagClasses[flagIndex]}"></i>`;
  } else {
    /** common image/icon could be added for new options */
  }
  return `${prefix}${data.label}`;
}
```
![Screenshot_24](https://user-images.githubusercontent.com/8354705/122295619-b98aec00-cef9-11eb-831a-ff27e7443e8d.png)

Issue after commit: 1ef9368302c3d

**Comment by sa-si-dev** [comment]
@Goatform I don't think this is an issue.

The purpose of this plugin is to improve performance by rendering minimum no.of. options at a time and render more options on scroll.
So when you scoll on options it will call `sampleLabelRenderer` function for each options that is visible.

 I don't find that the `sampleLabelRenderer` is affecting the performance. But `console.log` inside the function affect the performance.

Calling `sampleLabelRenderer` function for 10K times with `console.log`, it take around 477ms

<img width="706" alt="Screenshot 2021-06-17 at 1 22 52 PM" src="https://user-images.githubusercontent.com/76465932/122355649-b29ec080-cf6f-11eb-8984-28b11c6c56bb.png">

But when you call it 100K times (10 times previous) without `console.log`, it take only 6ms

<img width="706" alt="Screenshot 2021-06-17 at 1 30 31 PM" src="https://user-images.githubusercontent.com/76465932/122356233-39539d80-cf70-11eb-931e-dd13fbdbb390.png">


So try to keep the logic inside `sampleLabelRenderer` function minimal for better performance.

**Comment by Goatform** [comment]
Hmm, I get the point of your approach now, thank you for explaining it precisely @sa-si-dev
