### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ahsynv** [sa-si-dev/virtual-select#43]
Hi, i dont know if its possible with current version of the package or not, but i would know is it possible to do (or add in the next version), the possibility to init virtual select more easly for already existing for elements ?

For example if i have already this select

`<select name="test">
    <option value="dog">Dog</option>
    <option value="cat">Cat</option>
    <option value="hamster">Hamster</option>
    <option value="parrot">Parrot</option>
    <option value="spider">Spider</option>
    <option value="goldfish">Goldfish</option>
</select>`

just init it with that without reenter all options ? Virtual select can get all options automatically from "select" tag ?

`VirtualSelect.init({
  ele: 'select'
});`

**Comment by sa-si-dev** [comment]
@ahsynv please refer [How to initiate plugin from native <select> element?](https://github.com/sa-si-dev/virtual-select/discussions/45)
