### ISSUE TITLE
How to mark selected options

### ISSUE THREAD

**Issue by abujalka** [sa-si-dev/virtual-select#46]
Hi,

please is it possible to mark the selected options in some way similar to the blocked options?
I use the setOptions () method to add options.
I can then mark the disabled options with the setDisabledOptions () method, but I would also need to mark the selected options, for example with the method or with the properties in the options field.

well thank you
Tony

**Comment by sa-si-dev** [comment]
@abujalka you could use setValue() method.

https://sa-si-dev.github.io/virtual-select/#/methods?id=setvalue
