### ISSUE TITLE
Enhancements - Text after selecting item, Trigger on close select, Container for selected items

### ISSUE THREAD

**Issue by abujalka** [sa-si-dev/virtual-select#47]
Hi, I have suggestions for the following improvements:

1. Set to display the placeholder after selecting an item
a) I have entered the placelholder "Town" and at the same time maxValues to "50" ... after selecting one item, "1/50 option selected" would not be displayed, but for example "1/50 | Town"
b) in case I did not have maxValues set, "1 | Town" would be displayed
c) the number of selected items (1/50, 1) could be in an element to which a class could be added

2. If I open select, select items, and then close select, the "vscomp-wrapper" element gets the "closed" class. A trigger could be added to this action.

3. Container settings for selected items. After selecting an item, an element with the value of the selected item would be added to the container. Clicking on this item would remove it from among the selected items in the select.

well thank you
Tony

**Comment by sa-si-dev** [comment]
@abujalka, thanks for your suggestions.

Regarding 1 and 3, I will work on them in future releases.

Regarding 2,

- We have `close()` method to close the dropdown programmatically ([more details](https://sa-si-dev.github.io/virtual-select/#/methods?id=close))
- We have `open/close` events to listen ([more details](https://sa-si-dev.github.io/virtual-select/#/events?id=open-close))

**Comment by abujalka** [comment]
Thank you very much for your answer.

I apologize for being inattentive to point number 2.
I still thought that it would be nice if an event was added after clearing the select (click on the element with the class vscomp-clear-button)
I do not want to perform the action after each change (change event), but only if the change is final - I close or clear the select.

I look forward to the future releases.

Sincerely
Tony

**Comment by sa-si-dev** [comment]
> I still thought that it would be nice if an event was added after clearing the select (click on the element with the class vscomp-clear-button)
I do not want to perform the action after each change (change event), but only if the change is final - I close or clear the select.

Sorry, I am not getting your requirement here. Could you please explain with some real-time scenarios?

**Comment by abujalka** [comment]
Hi, I'll try to explain.

I have a virtual select in which I have cities.
I have a "Search" button that shows the number of items that match the filter.

1. Open a virtual select with cities and check 10 items.
2. Close the virtual select with cities.
3. I will recalculate how many items match the filter and update the number in the "Search" button.
4. Then I clear the virtual select with cities using an element with the class "vscomp-clear-button".
5. I need to repeat point no.3

well thank you

**Comment by sa-si-dev** [comment]
@abujalka If I understand your requirement correctly, you could implement your case using the `change` event itself as below.

```js
function onValueChange() {
  let count = this.value.length;

  /** if any value selected, exit function */
  if (count > 0) {
    return;
  }

  /**
   * add your logic here to execute on clearing value
   */
}
```

**Comment by sa-si-dev** [comment]
@abujalka I have implemented your 1) and 2) requirements and they are available in the [release v1.0.12](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.12)


1) optionsSelectedText - Text to use when displaying no.of values selected text (i.e. 3 options selected)
2) reset event ([more details](https://sa-si-dev.github.io/virtual-select/#/events?id=reset))

**Comment by abujalka** [comment]
Hi,

1.
If I have options maxValues set, it shows me "number of checked / maxValues | optionsSelectedText".
If I don't have options maxValues set, then after checking the first option, it shows me the text of this option, and after checking the next option, it shows me "2 | optionsSelectedText".
I tried to work around it by setting maxValues, but if I check all the options, it is not possible to translate the text "All".

I suggest that "1" + optionsSelectedText be displayed immediately after checking the first option.

I will also ask you to translate "All" when all options are checked.

2.
The reset event works perfectly.

Thank you very much
Tony

**Comment by sa-si-dev** [comment]
@abujalka, I will implement 1) in the future release.

**Comment by sa-si-dev** [comment]
@abujalka, Features you have requested are available in the [release v1.0.14](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.14)

1) New classes added as you requested `vscomp-selected-value-count` and `vscomp-max-value-count`
2) showValueAsTags ([more details](https://sa-si-dev.github.io/virtual-select/#/examples?id=show-values-as-tags))
3) alwaysShowSelectedOptionsCount
4) disableAllOptionsSelectedText
5) allOptionsSelectedText

**Comment by abujalka** [comment]
Hi.

First of all, I would like to thank you for your very quick approach to resolving my requests.

All my requirements were met, only 1 was implemented in a different way than I imagined - container settings.

My idea was that a property would be added to set the id of the container to which the selected items would be added. The container would not have to be located directly in the virtual select component, but anywhere on the page. Would it be possible to implement it?

well thank you
Sincerely
Tony

**Comment by sa-si-dev** [comment]
> Hi.
> 
> First of all, I would like to thank you for your very quick approach to resolving my requests.
> 
> All my requirements were met, only 1 was implemented in a different way than I imagined - container settings.
> 
> My idea was that a property would be added to set the id of the container to which the selected items would be added. The container would not have to be located directly in the virtual select component, but anywhere on the page. Would it be possible to implement it?
> 
> well thank you
> Sincerely
> Tony

@abujalka sorry, rendering any content outside of the dropdown doesn't look like a generic feature that could be part of the plugin.

But you could implement it in your project by rendering selected values anywherer on value change.
