### ISSUE TITLE
publish this package to npm registry

### ISSUE THREAD

**Issue by kkkisme** [sa-si-dev/virtual-select#48]
publish this package to npm registry that we can download it conveniently

**Comment by sa-si-dev** [comment]
@kkkisme thanks for your suggestion. I will publish it in NPM.

**Comment by sa-si-dev** [comment]
@kkkisme I have published this plugin in NPM.

[https://www.npmjs.com/package/virtual-select-plugin](https://www.npmjs.com/package/virtual-select-plugin)
