### ISSUE TITLE
Ability to add aliases to labels for searching

### ISSUE THREAD

**Issue by yahyaerturan** [sa-si-dev/virtual-select#5]
Great plugin, thank you.

It would be really nice to add aliases to labels for searching. I am using this library instead of bootstrap-select with BS5.

```html
    <option value="27" data-aliases="turkey,middle east">Istanbul</option>
    <option value="43" data-aliases="england,united kingdom,europe">London</option>
```

This is the final html I proposed. We should be able to find "London" option when we type `england` or `europe` for example.

**Comment by sa-si-dev** [comment]
It is an interesting feature to have.

I will work on it in the future release.

Thanks for your suggesion.

**Comment by frg** [comment]
@yahyaerturan This functionality has been added in #7 however since this plugin does not deal with importing the options from the DOM directly you'll have to query and parse the terms manually.

```javascript
const select = document.querySelector("#select");
const options = Array.prototype.slice.call(select.options)
    .map(x => {
        return {
            label: x.text,
            value: x.value,
            terms: x.getAttribute("data-aliases").split(","),
        }
    });
 ```

**Comment by yahyaerturan** [comment]
If I get it right, this will result in a second mapping of json data as we set options by json when initializing? The html I wrote here as a sample of final output. Will this be done after initializing virtual select? More generic solution might be defining searchable json keys when initialising and leave the rest to the backend.

**Comment by frg** [comment]
>here as a sample of final output.

This plugin does not generate a select HTML element with options tags.

You would initialize the plugin as shown below
```javascript
VirtualSelect.init({
  ele: '#sample-select',
  options: [
    { label: 'Options 1', value: '1' },
    { label: 'Options 2', value: '2' },
    { label: 'Options 3', value: '3' },
  ],
});
```

**Comment by yahyaerturan** [comment]
👍 Looks great. Thank you.. Next release will be a loaded gun :)

**Comment by sa-si-dev** [comment]
> @yahyaerturan This functionality has been added in #7 however since this plugin does not deal with importing the options from the DOM directly you'll have to query and parse the terms manually.
> 
> ```js
> const select = document.querySelector("#select");
> const options = Array.prototype.slice.call(select.options)
>     .map(x => {
>         return {
>             label: x.text,
>             value: x.value,
>             terms: x.getAttribute("data-aliases").split(","),
>         }
>     });
> ```

@frg, it is not recommanded to read data from DOM element. The main problem, this plugin trying to solve is, reduce the no.of DOM element.

It is good to handle data in JS object for better performance.

**Comment by frg** [comment]
I agree, if I understood @yahyaerturan correctly by his example he already has a select element on his page which he's like to convert to using the plugin. I could have misunderstood.

**Comment by sa-si-dev** [comment]
> Great plugin, thank you.
> 
> It would be really nice to add aliases to labels for searching. I am using this library instead of bootstrap-select with BS5.
> 
> ```
>     <option value="27" data-aliases="turkey,middle east">Istanbul</option>
>     <option value="43" data-aliases="england,united kingdom,europe">London</option>
> ```
> 
> This is the final html I proposed. We should be able to find "London" option when we type `england` or `europe` for example.

@yahyaerturan  as you requested, we have implemented the feature to allow using alias for searching.

This feature is available in the [release v.1.0.3](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.3) ([more details](https://sa-si-dev.github.io/virtual-select/#/examples?id=using-alias-for-searching))
