### ISSUE TITLE
Incorrect behavior of tooltips

### ISSUE THREAD

**Issue by abujalka** [sa-si-dev/virtual-select#52]
Hi,

I have my other observations with the use of virtual select.

I use the tooltip plugin because not all of my options are fully visible.

1. Open the virtual select, move the cursor to the option where the tooltip is displayed. Then I scroll but the tooltip remains displayed. It doesn't look nice, and I don't think it's even right.

2. Open the virtual select, move the cursor to the option where the tooltip is not displayed. Then I scroll and stop scrolling so that the cursor is set to an option that is not completely visible. The tooltip does not appear immediately, but only when I move the cursor.

If you fixed it, it would be great.

well thank you
Sincerely
Tony

**Comment by sa-si-dev** [comment]
@abujalka I will fix them in the future release.

Thanks for letting me know.

**Comment by sa-si-dev** [comment]
@abujalka it was an issue in the tooltip plugin.

It has been fixed in the release [tooltip v1.0.15](https://github.com/sa-si-dev/tooltip/releases/tag/v1.0.15)
