### ISSUE TITLE
Dropbox does not float to the forefront 

### ISSUE THREAD

**Issue by mjesteve** [sa-si-dev/virtual-select#53]
Hi, first of all I think it's a great job you've done with virtual-select, it works very well.
I belong to the Apache Royale community [[1](https://apache.github.io/royale-docs/)] and for this year's ApacheCon I'm preparing a set of examples of integration with JS libraries. Virtual Select seemed to me a very good example to be part of the project (Echarts [[2](https://echarts.apache.org/en/index.html)], jsCalendar [[3](https://gramthanos.github.io/jsCalendar/index.html)], fullCalendar [[4](https://fullcalendar.io/)] are some others).

I have found some things that have not worked correctly but until I know the library well and verify that they are real errors and not errors due to lack of knowledge I am going to tell you the one that I think is the most important and that is blocking the integration: the visibility and positioning of the dropbox.

As they say that a picture is worth a thousand words....

![image](https://user-images.githubusercontent.com/55754195/128151033-d3070d4a-caea-49be-abbd-3685ed7fddff.png)

The component on the left is a virtual-select and the one on the right is a Jewel VirtualComboBox native to Royale.
As you can see, the dropbox of the virtual-select stays inside the parent container, it doesn't float to the foreground, which causes it to be cut off. The same behaviour is reproduced with keepAlwaysOpen=false:

![image](https://user-images.githubusercontent.com/55754195/128152020-6f0ab1cf-06cd-4683-91d1-82a7c4584fee.png)

I don't come from the Js-CSS world and this is a bit too big for me.... :P 
Is there any chance that the dropbox would not be displayed inline?

In the case of the Jewel VirtualComboBox the dropbox is created as a layer in the first view level, which ensures that its display is always in the foreground, floating above any other layout component.
If this were a feasible option for you, would it be a possible solution? And if not... Can you think of a solution?

Thank you very much for your attention and congratulations for this great component.

Hiedra

**Comment by mjesteve** [comment]
Just to add another example... this time with the display priority:

![image](https://user-images.githubusercontent.com/55754195/128168943-2f5854ac-37c6-45cd-8102-78b35e18af68.png)

If you notice, the dropbox in the top select is below the fixed dropbox. This time it has to do with the z-index. The fixed dropbox has z-index=1 and the top dropbox "also". Could you leave z-index=1 when it is fixed and z-index=2x when it is floating?

**Comment by rjsaci** [comment]
@mjesteve Thank you for considering this plugin to use in your project.

1) This issue is happing because the plugin is rendered inside an element that has overflow hidden or scroll property. To fix this, dropbox needs to be rendered at the end of the body element instead of inside the virtual select wrapper. 

2) I will increase the z-index of floating dropbox as you suggested.

Will implement the above items in the future release.

**Comment by sa-si-dev** [comment]
@mjesteve Thank you for considering this plugin to use in your project.

1) This issue is happing because the plugin is rendered inside an element that has overflow hidden or scroll property. To fix this, dropbox needs to be rendered at the end of the body element instead of inside the virtual select wrapper. 

2) I will increase the z-index of floating dropbox as you suggested.

Will implement the above items in the future release.

**Comment by mjesteve** [comment]
Thank you very much sa-si-dev.
Yesterday I started to set up the development environment with vsCode to be able to do debug tests but I still don't have it. Is there any document about this in the repository?

Thanks for your interest.

Hiedra

**Comment by sa-si-dev** [comment]
> Thank you very much sa-si-dev.
> Yesterday I started to set up the development environment with vsCode to be able to do debug tests but I still don't have it. Is there any document about this in the repository?
> 
> Thanks for your interest.
> 
> Hiedra

Please check [here](https://github.com/sa-si-dev/virtual-select/discussions/56)

**Comment by mjesteve** [comment]
Thx.

**Comment by sa-si-dev** [comment]
@mjesteve this feature is available in the [release v1.0.15](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.15)

Use `dropboxWrapper: 'body'` property to avoid dropbox hiding.

**Comment by mjesteve** [comment]
I will try it, thank you very much.

**Comment by mjesteve** [comment]
It works very well:

![GIF 17-08-2021 13-15-33](https://user-images.githubusercontent.com/55754195/129716807-dec12d74-3fcb-4be2-9ae2-0995d0f1a492.gif)

I will definitely incorporate it into my projects ;)
Thanks sa-si-dev

**Comment by sa-si-dev** [comment]
> It works very well:
> 
> ![GIF 17-08-2021 13-15-33](https://user-images.githubusercontent.com/55754195/129716807-dec12d74-3fcb-4be2-9ae2-0995d0f1a492.gif)
> 
> I will definitely incorporate it into my projects ;)
> Thanks sa-si-dev

Thank you
