### ISSUE TITLE
Disabled attribute

### ISSUE THREAD

**Issue by smagret** [sa-si-dev/virtual-select#57]
Hi, awesome work you have done here,
I would like to ask how to set the dropdown as `disabled`, same as `<select>` inputs have the attribute `disabled` to not let the user interact with the input, I would like to do the same with the `vscomp`, I have tried adding the attribute/class to various divs and/or to the hidden input but it seems to have no effect and I can't find a way around it.

If there is a way, could you please show how it is done? And if not, could you please add the feature/option in the next release?
I think it would be pretty helpful to set the vscomp as disabled just like all other inputs.

Thank you!

**Comment by sa-si-dev** [comment]
@smagret thank you for the suggestion.

I will implement it in the future release.

**Comment by sa-si-dev** [comment]
@smagret this feature is available in the [release v1.0.15](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.15)

```js
/** disable element */
document.querySelector('#sample-select').setAttribute('disabled', '');

/** enable element */
document.querySelector('#sample-select').removeAttribute('disabled');
```

**Comment by yahyaerturan** [comment]
As a positive remark, documentation misses this feature. Today I need this one and remember saw this in on of the emails as I follow the repo. But for a new one it might be a challenge.

**Comment by sa-si-dev** [comment]
@yahyaerturan thanks for informing me. I will add that in the documentation.

**Comment by bes-internal** [comment]
@sa-si-dev Why are you only marking the item itself disabled? You just make it visually inaccessible. The hidden input also needs to be with attr disabled. Otherwise, it is sent to the server from the form. Disabled items should not be sent to the server.

**Comment by sa-si-dev** [comment]
> @sa-si-dev Why are you only marking the item itself disabled? You just make it visually inaccessible. The hidden input also needs to be with attr disabled. Otherwise, it is sent to the server from the form. Disabled items should not be sent to the server.

@bes-internal thanks for letting me know it. I will do the required changes in the future release.

**Comment by sa-si-dev** [comment]
@bes-internal this issue has been fixed in the release [v1.0.21](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.21)

Use the below methods to disable/enable dropdown

```js
document.querySelector('#sample-select').disable();

document.querySelector('#sample-select').enable();
```

**Comment by squareclouds** [comment]
I just realised this is not done 100%. virtual-selects can still be edited via keyboard tab. could you please check this? this can be confusing for the user

**Comment by kosirm** [comment]
This have some problem... I can't make a toggle.
This is not working:
```
            if (disabled === null) {
                select.disable()
            }
            else{
                select.enable()
            }
```
I tried many things like this:
```
            var justOnce = (function (element, disabled) {
                var executed = false;
                return function (element, disabled) {
                    if (!executed) {
                        executed = true;
                        if(disabled == null){
                            element.disable()
                        }
                        else{
                            element.enable()
                        }
                    }
                };
            })();

            let select = e.target.parentNode.parentNode.firstChild.nextSibling //my specific path
            let disabled = select.getAttribute("disabled")
            justOnce(select,disabled)
```

However `select.getAttribute("disabled")` returns two results...
Please help!

**Comment by squareclouds** [comment]
@sa-si-dev hmmmm have you had a chance to check this? :)
