### ISSUE TITLE
setOptions does not update items created in dropbox

### ISSUE THREAD

**Issue by mjesteve** [sa-si-dev/virtual-select#58]
Hi, 
I think there is a small bug with the setOptions method, it does not update the pre-existing options in the dropdown:

![GIF 15-08-2021 0-54-46](https://user-images.githubusercontent.com/55754195/129462211-62ac4fef-d5f6-4d6d-aedb-5edab0f1210d.gif)

if instead of using setOptions I use setServerOptions we get the expected result:

![GIF 15-08-2021 1-16-23](https://user-images.githubusercontent.com/55754195/129462461-42c6496d-a97a-4800-90ef-0a1edf92b03f.gif)

Hiedra.

**Comment by sa-si-dev** [comment]
@mjesteve this is expected behavior only. `setOptions()` method would override existing options with new options.

**Comment by mjesteve** [comment]
Thanks for the clarification ;)
I will continue to use setServerOptions because I want to see the dataprovider changes as soon as I send them to it and not when I move or select any.

Thanks for replying.
