### ISSUE TITLE
How to add `?term=..` appropriately when remote url already have query parameters.

### ISSUE THREAD

**Issue by yahyaerturan** [sa-si-dev/virtual-select#61]
Hi again.

I have a api-based remote url to fetch results on search. Sth like: `domain.com/resource?active=1&position=asc`. But when search, plugin is not aware that I have already a query string in remote url so it adds blindly '?term=....' to the end of url. Is there a way to make sure plugin adds term as `&term=...` if query string is already exists in the given remote url?

**Comment by sa-si-dev** [comment]
@yahyaerturan this plugin doesn't have any API related code like creating API URL and calling API.

These logic should be handled by the project developer to use server search feature.

Could you please share the code you are using to initiate the plugin with `onServerSearch` callback function

**Comment by yahyaerturan** [comment]
`onServerSearch` it is. Figure out how to do.. Thank you for the tip.
