### ISSUE TITLE
setDisabledOptions removes current selection

### ISSUE THREAD

**Issue by kurkle** [sa-si-dev/virtual-select#62]
# Context

Multiple virtual selects for same set of "things", only allowing a "thing" in one select. So when a value changes in a selects, that value is disabled from other selects. Selecting single value.

# Current behavior

Previous selection is lost, even if its not in the disabled list.

# Expected behavior

Disabled status of the elements is updated, selection is preserved.

**Comment by sa-si-dev** [comment]
@kurkle, thanks for letting me know it. I will check and fix them in the future release.
