### ISSUE TITLE
The github button in homepage has an invalid link

### ISSUE THREAD

**Issue by kurkle** [sa-si-dev/virtual-select#69]
https://sa-si-dev.github.io/virtual-select

![image](https://user-images.githubusercontent.com/27971921/137318436-882537a6-1225-4f3f-9ec9-b1ed460cbd48.png)

**Comment by sa-si-dev** [comment]
@kurkle this issue has been fixed in the [release v1.0.18](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.18)
