### ISSUE TITLE
Feature: Support selecting a range of items from the list

### ISSUE THREAD

**Issue by kurkle** [sa-si-dev/virtual-select#70]
It would be nice to be able to select a range of items, like in plain select.

Using click .. shift + click and/or dragging a range while keeping mouse button pressed.

**Comment by sa-si-dev** [comment]
@kurkle this feature has been implemented in the [release v1.0.18](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.18)

**Comment by kurkle** [comment]
This could be extended with the ability to de-select a range.

- if the shift-clicked item is already selected, remove selection from the range.

I'm not certain this would be a behavior everyone expects though. 

A default `<select multiple>` stores the non-shift clicked option as a reference and shift-clicks after that replace the whole selection with the new range. IMO that would not be as good.
