### ISSUE TITLE
Value with comma and multiple

### ISSUE THREAD

**Issue by Jaaap** [sa-si-dev/virtual-select#71]
When you use `multiple:true` and have a value with a comma, you get that value split into 2 seperate values.
Example:
```javascript
VirtualSelect.init({
	ele: '#sample-select',
	multiple: true,
	options: [
		{ label: 'Options 1', value: '1' },
		{ label: 'With comma', value: '2,3' },
	],
});
```
Selecting both values will result in the hidden input having the value "1,2,3".

**Comment by sa-si-dev** [comment]
@Jaaap this issue got fixed in the [release v1.0.19](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.19)

To avoid this issue, use `setValueAsArray: true` property. By doing so, multiple select's value would be available as JSON string in the hidden input (e.g. '["1", "2"]')

**Comment by Jaaap** [comment]
Ah thank you for this solution.
I realise i have not made clear what i want to achieve:
To make it behave exactly like a `select[multiple]` which means a separate `input[type=hidden]` for each value.

That way we can use it as a progressive enhancement on an existing select.
Is that feasible?

**Comment by sa-si-dev** [comment]
> Ah thank you for this solution. I realise i have not made clear what i want to achieve: To make it behave exactly like a `select[multiple]` which means a separate `input[type=hidden]` for each value.
> 
> That way we can use it as a progressive enhancement on an existing select. Is that feasible?

@Jaaap, The concept of this plugin is to improve the performance by avoiding the number of DOM elements on the page.
If we add a separate `input[type=hidden]` for each option, this might affect the performance.

**Comment by Jaaap** [comment]
Yes your performance is awesome!
I think it will still be acceptable if you start without any `input[type=hidden]` for `multiple` and dynamically add `input[type=hidden]`'s when users select options.

**Comment by sa-si-dev** [comment]
@Jaaap I will try this and use it if not affecting the performance.

**Comment by Jaaap** [comment]
Gentle reminder.
Is this still on your radar?

**Comment by sa-si-dev** [comment]
> Yes your performance is awesome!
> I think it will still be acceptable if you start without any `input[type=hidden]` for `multiple` and dynamically add `input[type=hidden]`'s when users select options.

I tried this method. Even though we add hidden input for only selected options, there may be a case where select all action would add hidden input for all options available.
