### ISSUE TITLE
Compatibility with internet explorer

### ISSUE THREAD

**Issue by RicPap** [sa-si-dev/virtual-select#74]
Hi,
The library works fine on chrome, but I'm having some troubles on IE, the library is imported inside my project not by url.
These are the errors from the console:
Couldn't initiate Virtual Select
Object doesn't support property or method 'forEach'
virtual-select.min.js (5,8622).
Any suggestions?
Thank you for your help.

**Comment by sa-si-dev** [comment]
@RicPap this issue got fixed in the [release v1.0.19](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.19)
