### ISSUE TITLE
Omitting select all checkbox on multiple

### ISSUE THREAD

**Issue by yahyaerturan** [sa-si-dev/virtual-select#8]
When `multiple: true` and `search: true`, we can see select all checkbox. Seems reasonable, but when we start to type to search and no result found, entered text and check all box in display. I believe it is not good for ux. Even me, I clicked the checkbox and selected all 4500 record at once. I believe it should be omitted or have an option to not show select all checkbox. I am now actively using your plugin on a live project, that's why I am taking liberty to propose enhancement to make this library get what it worth. Great lib!

**Comment by frg** [comment]
I've run into this confusion myself. In fact, I was working on a change where the select all checkbox while searching would select only the options that are currently in the list, however, it ended up being more confusing.

Disabling the select all option would be the best compromise.

**Comment by sa-si-dev** [comment]
@frg, Yes we can make it as a core feature as you suggest.

Thank you for your contribution.

**Comment by sa-si-dev** [comment]
> When `multiple: true` and `search: true`, we can see select all checkbox. Seems reasonable, but when we start to type to search and no result found, entered text and check all box in display. I believe it is not good for ux. Even me, I clicked the checkbox and selected all 4500 record at once. I believe it should be omitted or have an option to not show select all checkbox. I am now actively using your plugin on a live project, that's why I am taking liberty to propose enhancement to make this library get what it worth. Great lib!

@yahyaerturan  as you requested, we have implemented the feature to disabling Select all checkbox, if search field has value.

This feature is available in the [release v.1.0.3](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.3)
