### ISSUE TITLE
Error on mobile

### ISSUE THREAD

**Issue by ERIS-VN** [sa-si-dev/virtual-select#83]
It not working after clear value

**Comment by sa-si-dev** [comment]
> It not working after clear value

@ERIS-VN I will check and fix it in the future release. Thanks for letting me know it.

**Comment by sa-si-dev** [comment]
@ERIS-VN this issue has been fixed in the release [v1.0.20](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.20)
