### ISSUE TITLE
Drop-in replacement for <select>

### ISSUE THREAD

**Issue by bes-internal** [sa-si-dev/virtual-select#85]
The idea is to drop-in replace regular `<select>` with virtual-select. Including for backward compatibility. 

Need to deepen the idea of  [using data-* attributes on node](https://sa-si-dev.github.io/virtual-select/#/properties?id=using-properties-as-dom-attributes). There are limitations as indicated in the documentation. Following properties are not allowed to use as attribute:

1. options (need to read the provided `<option>` inside `<select>`)
2. disabledOptions (need to read `disabled` attr on `<option>`)
3. selectedValue (need to read `selected` attr on `<option>`)
4. onServerSearch, labelRenderer (I do not know)

For all of the above, there should be a warning in the documentation that this method is only for backward compatibility and slow on a lot of options. But with a small number of options, this is not a problem at all.

Now initialization on the select, as expected, does not give a result because all the work happens inside the element. Here we may need to add the `replace` property or unconditionally replace depending on Element.tagName.

P.S. 
It will be great. Magic transformation of all select on page into a new-era-select.
Yes, this is something from a world where the idea of everything at the front has not yet won, but that is why this project was also created, right?

**Comment by sa-si-dev** [comment]
@bes-internal this is a good suggestion. I will implement it in the future release. Thanks for your support to improve this plugin.

**Comment by bes-internal** [comment]
I would like to get the following parameters (passed during initialization) back in the form of node propertys (as in a regular `<select>` node):

- [x] .value  (already done)
- [ ] .name
- [ ] .disabled
- [ ] .form (for use as `event.target.form` where target is [virtual-select](https://github.com/sa-si-dev/virtual-select). Not necessary but desirable)
- [x] .multiple (already done)
- [ ] .required 
- [ ] .options
- [ ] .length
- [ ] .selectedOptions (already done as method `getSelectedOptions()` but not as property)
- [ ] .autofocus

@sa-si-dev

**Comment by sa-si-dev** [comment]
> I would like to get the following parameters (passed during initialization) back in the form of node propertys (as in a regular `<select>` node):
> 
> - [x] .value  (already done)
> - [ ] .name
> - [ ] .disabled
> - [ ] .form (for use as `event.target.form` where target is [virtual-select](https://github.com/sa-si-dev/virtual-select). Not necessary but desirable)
> - [x] .multiple (already done)
> - [ ] .required 
> - [ ] .options
> - [ ] .length
> - [ ] .selectedOptions (already done as method `getSelectedOptions()` but not as property)
> - [ ] .autofocus
> 
> @sa-si-dev 

@bes-internal I will implement this changes in the future release.

**Comment by sa-si-dev** [comment]
> The idea is to drop-in replace regular `<select>` with virtual-select. Including for backward compatibility.
> 
> Need to deepen the idea of [using data-* attributes on node](https://sa-si-dev.github.io/virtual-select/#/properties?id=using-properties-as-dom-attributes). There are limitations as indicated in the documentation. Following properties are not allowed to use as attribute:
> 
> 1. options (need to read the provided `<option>` inside `<select>`)
> 2. disabledOptions (need to read `disabled` attr on `<option>`)
> 3. selectedValue (need to read `selected` attr on `<option>`)
> 4. onServerSearch, labelRenderer (I do not know)
> 
> For all of the above, there should be a warning in the documentation that this method is only for backward compatibility and slow on a lot of options. But with a small number of options, this is not a problem at all.
> 
> Now initialization on the select, as expected, does not give a result because all the work happens inside the element. Here we may need to add the `replace` property or unconditionally replace depending on Element.tagName.
> 
> P.S. It will be great. Magic transformation of all select on page into a new-era-select. Yes, this is something from a world where the idea of everything at the front has not yet won, but that is why this project was also created, right?

@bes-internal This feature is available in the [release v1.0.22](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.22)  ([more details](https://sa-si-dev.github.io/virtual-select/#/?id=initialize-from-native-select-element-not-recommended))

**Comment by sa-si-dev** [comment]
> I would like to get the following parameters (passed during initialization) back in the form of node propertys (as in a regular `<select>` node):
> 
> * [x]  .value  (already done)
> * [ ]  .name
> * [ ]  .disabled
> * [ ]  .form (for use as `event.target.form` where target is [virtual-select](https://github.com/sa-si-dev/virtual-select). Not necessary but desirable)
> * [x]  .multiple (already done)
> * [ ]  .required
> * [ ]  .options
> * [ ]  .length
> * [ ]  .selectedOptions (already done as method `getSelectedOptions()` but not as property)
> * [ ]  .autofocus
> 
> @sa-si-dev

@bes-internal This feature is available in the [release v1.0.22](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.22)

.selectedOptions - This prop is not implemented as  we already have `getSelectedOptions()` method and it might affect the performance.

**Comment by bes-internal** [comment]
Great. Thanks!

> .selectedOptions

the goal is for third-party software to work with this element as with a usual `<select>`
