### ISSUE TITLE
Element's initial state - disabled

### ISSUE THREAD

**Issue by bes-internal** [sa-si-dev/virtual-select#86]
1.0.21 introduced methods `disable()`/`enable()`. Along with this there were problems:

1. need to set the initial state of the element as definition (property)
2. maybe need to fire `change` the event on `disable()`/`enable()`
3. analog of a property `silentInitialValueSet ` or totaly rework this idea

**Comment by sa-si-dev** [comment]
@bes-internal thanks for your suggestions. I will check and implement 1 and 2 points in the future release.

Could you please explain your 3rd point.

**Comment by bes-internal** [comment]
If you implement `change` events on the `disable()`/`enable()` methods AND if you set the initial state "disabled" through the internal way init->`disable()`, then you will need an option that prevents such an event from being triggered (like property `silentInitialValueSet`).
Therefore, perhaps it is worth not using events during the initial initialization, both for setting the selected value and for disabled  state at all?

**Comment by sa-si-dev** [comment]
> If you implement `change` events on the `disable()`/`enable()` methods AND if you set the initial state "disabled" through the internal way init->`disable()`, then you will need an option that prevents such an event from being triggered (like property `silentInitialValueSet`).
> Therefore, perhaps it is worth not using events during the initial initialization, both for setting the selected value and for disabled  state at all?

@bes-internal thanks for the explanation. I will think about it and implement it.

**Comment by sa-si-dev** [comment]
@bes-internal I have added support to disable dropdown while initialization with new property `disabled: true`.

This feature is available in the [release v1.0.22](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.22)

I don't think triggering the `change` event on disabling/enabling dropdown would be an expected behavior as there is no change in the value.
