### ISSUE TITLE
add setServerOptions method to docs

### ISSUE THREAD

**Issue by bes-internal** [sa-si-dev/virtual-select#88]
add to documentation
- setServerOptions method
- highlight as one of the main features that you can get results from the server. When I was looking for your project among similar ones, it was one of the decisive factors that you do not need to implement the auxiliary code yourself
- remove this example https://sa-si-dev.github.io/virtual-select/#/methods?id=disable-element or move to Discussions as "how to make an element appear to be disabled"

**Comment by sa-si-dev** [comment]
@bes-internal thanks for your support. I will update the docs.

**Comment by sa-si-dev** [comment]
@bes-internal I have updated the above details in the documentation
