### ISSUE TITLE
ele property should use querySelectorAll

### ISSUE THREAD

**Issue by bes-internal** [sa-si-dev/virtual-select#89]
`ele` property takes String values for use in querySelector, but should use querySelectorAll for this definition works:

```
VirtualSelect.init({ ele: 'select' });
```
(all `select` tags on page)

ref: https://github.com/sa-si-dev/virtual-select/blob/729a1aec380816f67a9aef96fc6a1161a65e2548/src/virtual-select.js#L2577

**Comment by sa-si-dev** [comment]
@bes-internal thanks for letting me know it. I will fix this issue in the future release.

**Comment by sa-si-dev** [comment]
@bes-internal this issue has been fixed in the [release v1.0.23](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.23)
