### ISSUE TITLE
Max number of selected items

### ISSUE THREAD

**Issue by yahyaerturan** [sa-si-dev/virtual-select#9]
It would be very useful to have an option max number of selected items.

For example, select max 5 profiles to follow..

**Comment by frg** [comment]
What should happen on the 6th option selection? Should it do nothing? Or should it overwrite a previous selection?

**Comment by yahyaerturan** [comment]
Before replying, I have checked other libraries on how they do. Overwriting or doing nothing is not a good solution. All they show a message (some show in search field, some show in footer of dropbox) that you can select maximum 5 items..

Another subject but I want to work in localization of this library, I will try to prepare a PR on next weekend hopefully.

**Comment by ahsynv** [comment]
Disabling all other options if limit is exceeded can be a good solution ?

**Comment by sa-si-dev** [comment]
I have planned to implement it as
  - showing no.of items selected with max limit (e.g 2/5 options selected) as value 
  - and disable all unselected items on selecting max no.of options.

**Comment by sa-si-dev** [comment]
@yahyaerturan as you requested, I have implemented this feature and it is available in the [release v.1.0.4](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.4)
