### ISSUE TITLE
Implement [required] validation

### ISSUE THREAD

**Issue by Jaaap** [sa-si-dev/virtual-select#91]
It would be awesome if it was possible to make the virtual-select `required`.
The element would have to get a red border if the form was submitted with a virtual-select without a value.
And the submit would also be prevented.

- Bonus kudo's if this `required` property were also toggleable on/off.
- The `form` can be accessd by checking `input[type=hidden]`'s `.form` property (might be null)

**Comment by sa-si-dev** [comment]
@Jaaap thanks for the suggestion. I will implement it in the future release.

**Comment by sa-si-dev** [comment]
@Jaaap this feature has been implemented and available in the [release v1.0.24](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.24)

- Use `required` property to make a dropdown mandatory
- Use [toggleRequired()](https://sa-si-dev.github.io/virtual-select/#/methods?id=togglerequired) method to toggle required value
- Use [validate()](https://sa-si-dev.github.io/virtual-select/#/examples?id=validation) method to validate the dropdown
