### ISSUE TITLE
Unable to override name when using native select as elem

### ISSUE THREAD

**Issue by Jaaap** [sa-si-dev/virtual-select#94]
It appears to be impossible to set the name of the virtual select's hidden `input` when `ele` points to an existing `select`:
```javascript
VirtualSelect.init({
	ele: 'select[name="cities1"]',
	name: 'cities2',
	multiple: true,
	setValueAsArray: true,
});
```
The name of the hidden `input` will be "cities1" but should be "cities2".

**Comment by sa-si-dev** [comment]
@Jaaap this is expected only. Value for any property would be assigned in the below order

- Default value
- Init method parameter
- Element attribute

When initializing the plugin from native select element, it would replace existing native element with virtual select element.

So new element should have same name only.

**Comment by Jaaap** [comment]
Ah i understand. We use this in combination with `setValueAsArray: true` which changes the format of the data sent to the server.
On the server side we need to be able to see whether a native `select` has posted `cities` data (for blind users and old browsers) OR the virtual-select has posted `cities` data in a different format.

I would suggest changing the order so that "Init method parameter" overwrites all others.

**Comment by sa-si-dev** [comment]
> Ah i understand. We use this in combination with `setValueAsArray: true` which changes the format of the data sent to the server.
> On the server side we need to be able to see whether a native `select` has posted `cities` data (for blind users and old browsers) OR the virtual-select has posted `cities` data in a different format.
> 
> I would suggest changing the order so that "Init method parameter" overwrites all others.

@Jaaap I don't think this should be the general behaviour.

When we initialize more then one drop-downs, we would give all common properties as init method parameter and drop-down specific properties as element attribute.

Workaround for your case is change the select element's name attribute value before calling init method.
