### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by Jaaap** [sa-si-dev/virtual-select#95]
It appears to be impossible to detect the use of a screenreader in JS so we have a need for virtual-select to also work well for people with blindness and other disabilities.

Please consider improving the Accessibility of virtual-select.

This link is a good read on Accessibility:
https://developer.mozilla.org/en-US/docs/Web/Accessibility
and more specific:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA

**Comment by sa-si-dev** [comment]
@Jaaap thanks for the suggestion. I will implement it in the future release.

**Comment by sa-si-dev** [comment]
@Jaaap I have implemented the accessibility feature based on the document https://www.w3.org/TR/wai-aria-practices/examples/combobox/combobox-select-only.html

Please check it and let me know if I have missed any accessibility attirbutes.

This feature is available in the [release v1.0.25](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.25)
