### ISSUE TITLE
setValueAsArray empty value

### ISSUE THREAD

**Issue by Jaaap** [sa-si-dev/virtual-select#96]
When using `setValueAsArray: true` it would be nice if the "empty value" or default value would be `[]` instead of the empty string.
Is that feasible?

**Comment by sa-si-dev** [comment]
@Jaaap you could use `emptyValue` property for your case.

This feature is available in the [release v1.0.25](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.25)
