### ISSUE TITLE
Labels with HTML

### ISSUE THREAD

**Issue by GitHunter0** [sa-si-dev/virtual-select#97]
Please, how can I use HTML tags to customize the labels? For example:
```
options = [
{ label: 'Option 1 <br> second row info', value: '1' },
{ label: '<em> Option 2 in Italic </em>', value: '2' }
]
```
Any help will be much appreciated.

**Comment by sa-si-dev** [comment]
> Please, how can I use HTML tags to customize the labels? For example:
> ```
> options = [
> { label: 'Option 1 <br> second row info', value: '1' },
> { label: '<em> Option 2 in Italic </em>', value: '2' }
> ]
> ```
> Any help will be much appreciated.

@GitHunter0 this case would work by default. To disable using HTML elements, set the property `enableSecureText: true`.

**Comment by GitHunter0** [comment]
Thank you @sa-si-dev , `virtual-select` is fantastic, incredibly useful.
