### ISSUE TITLE
Control Popup width

### ISSUE THREAD

**Issue by GitHunter0** [sa-si-dev/virtual-select#98]
Hey @sa-si-dev , it's me again.

I really like the style of having the Dropbox being displayed as Popup for __any screen size__, it is more beautiful, cleaner and allows to use more space of the screen to display more items. `virtual-select` Popup is so good that I even believe it should be the default style.

However, I can't find a way to control the Popup width, I have items with large label text that do not fit and `...` appears in the end.

Hence, is there a way to specify the Popup width? It could inherit the `dropboxWidth` value, for example.

It is the only thing preventing me to use the dropbox as popup everywhere.

Thank you

**Comment by sa-si-dev** [comment]
@GitHunter0  I will use `dropboxWidth` as max-width for popup box in the future release.

**Comment by sa-si-dev** [comment]
> Thank you very much @sa-si-dev !
> 
> To complement that, if possible, can you provide an alignment parameter (left, right, center) to the Popup as well?
> This is important to adjust the popup position to the user layout. For example, in a left sidebar-panel layout, it would be desirable that the popup stays on the right side, so that to keep the visibility of the sidebar controls.

@GitHunter0 I will implement it in the future release.

**Comment by GitHunter0** [comment]
Thanks again @sa-si-dev , I'm using `virtual-select` via this adaptation https://github.com/dreamRs/shinyvs , right now it is the best selector available in `R` in my opinion.

**Comment by sa-si-dev** [comment]
@GitHunter0 you could use `dropboxWidth` and `popupPosition` properties to change the width and position of the popup.

This feature is available in the [release v1.0.25](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.25)

**Comment by GitHunter0** [comment]
@sa-si-dev , you're the man! Thanks a lot!
